-- Quick syntax check for Anthropology_EpistemicInfrastructure
import FormalAnthropology.Anthropology_EpistemicInfrastructure

-- If this compiles, the main file has no syntax errors
#check Anthropology_EpistemicInfrastructure.infrastructure_necessity_theorem
#check Anthropology_EpistemicInfrastructure.maintenance_scaling_law
#check Anthropology_EpistemicInfrastructure.collapse_cascade_theorem
#check Anthropology_EpistemicInfrastructure.infrastructure_diversity_robustness_tradeoff
#check Anthropology_EpistemicInfrastructure.infrastructure_debt_accumulation
#check Anthropology_EpistemicInfrastructure.infrastructure_network_small_world
#check Anthropology_EpistemicInfrastructure.infrastructure_necessity_unconditional
#check Anthropology_EpistemicInfrastructure.maintenance_scaling_exact
#check Anthropology_EpistemicInfrastructure.critical_component_impact
#check Anthropology_EpistemicInfrastructure.infrastructure_debt_compounds
