/-
# Collective Ideogenesis: Basic Definitions

This file contains the foundational definitions for multi-agent ideogenesis
from MULTI_AGENT_IDEOGENESIS++:

- Definition 2.1: Agent
- Definition 2.2: Communication Channel
- Definition 2.3: Multi-Agent Ideogenetic System (MAIS)
- Definition 2.4: Collective State
- Definition 2.5: State Transition and Dynamics
- Definition 2.6: Forgetting Function

These definitions formalize the mathematics of communicating idea generators,
where ideas are generated by agents that exist in time, communicate imperfectly,
have distinct histories, and can die.
-/

import Mathlib.Data.Set.Basic
import Mathlib.Data.Set.Card
import Mathlib.Data.Nat.Defs
import Mathlib.Order.Basic
import Mathlib.Tactic
import FormalAnthropology.SingleAgent_Basic

namespace CollectiveIdeogenesis

open SingleAgentIdeogenesis

/-! ## Time Structure

A time structure provides the temporal framework for multi-agent dynamics.
In the finite case, we use natural numbers as discrete time steps.
-/

/-- A time structure is a preordered type with a minimal element.
    Definition 8.1 from MULTI_AGENT_IDEOGENESIS++.
    Note: We use Preorder rather than LinearOrder to maximize generality.
    This allows non-linear time models (branching time, partial orders). -/
class TimeStructure (T : Type*) extends Preorder T where
  /-- The beginning of history -/
  origin : T
  /-- Origin is the least element -/
  origin_le : ∀ t : T, origin ≤ t

/-- Natural numbers form a time structure with 0 as origin -/
instance : TimeStructure ℕ where
  origin := 0
  origin_le := Nat.zero_le

/-! ## Definition 2.1: Agent

An agent is a tuple (I_α, gen_α, mem_α, t_birth, t_death) where:
- I_α is the type of ideas agent α can hold
- gen_α : I_α → Set I_α is α's generation operator
- mem_α : Time → Set I_α is α's memory (ideas held at each time)
- t_birth, t_death are α's lifespan bounds
-/

/-- Agent identifier type -/
structure AgentId where
  id : ℕ
deriving DecidableEq

/-- An extended time value that can represent infinity (for immortal agents) -/
inductive ExtendedTime (T : Type*) where
  | finite : T → ExtendedTime T
  | infinite : ExtendedTime T
deriving DecidableEq

namespace ExtendedTime

variable {T : Type*} [Preorder T]

/-- Ordering on extended time: finite times come first, infinity is larger than all -/
def le : ExtendedTime T → ExtendedTime T → Prop
  | finite t, finite s => t ≤ s
  | finite _, infinite => True
  | infinite, finite _ => False
  | infinite, infinite => True

def lt : ExtendedTime T → ExtendedTime T → Prop
  | finite t, finite s => t < s
  | finite _, infinite => True
  | infinite, _ => False

instance : LE (ExtendedTime T) where
  le := le

instance : LT (ExtendedTime T) where
  lt := lt

theorem finite_lt_infinite (t : T) : (finite t : ExtendedTime T) < infinite := by
  simp only [LT.lt, lt]

theorem finite_le_finite {t s : T} : (finite t : ExtendedTime T) ≤ finite s ↔ t ≤ s := by
  simp only [LE.le, le]

theorem finite_lt_finite {t s : T} : (finite t : ExtendedTime T) < finite s ↔ t < s := by
  simp only [LT.lt, lt]

end ExtendedTime

/-- A raw agent without well-formedness constraints.
    This is a minimal structure that allows maximum flexibility in modeling.
    Use Agent for systems with standard temporal and memory constraints. -/
structure RawAgent (I : Type*) (T : Type*) where
  /-- Unique identifier for the agent -/
  agentId : AgentId
  /-- The agent's local idea space (embedded in the global space I) -/
  localIdeas : Set I
  /-- The agent's generation operator (restricted to their local space) -/
  generate : I → Set I
  /-- The agent's memory function: maps time to the set of ideas held -/
  memory : T → Set I
  /-- Time of birth (when the agent enters the system) -/
  birth : T
  /-- Time of death (when the agent exits); can be infinite for immortal agents -/
  death : ExtendedTime T

/-- An agent in the multi-agent ideogenetic framework.
    This is Definition 2.1 from MULTI_AGENT_IDEOGENESIS++. -/
structure Agent (I : Type*) (T : Type*) [Preorder T] extends RawAgent I T where
  /-- Birth must precede death -/
  birth_before_death : ExtendedTime.finite birth < death
  /-- Memory is only defined during the agent's lifetime -/
  memory_in_lifetime : ∀ t, memory t ⊆ localIdeas
  /-- Memory is empty before birth -/
  memory_before_birth : ∀ t, t < birth → memory t = ∅

/-- Birth precedes death for a raw agent -/
def RawAgent.hasBirthBeforeDeath {I T : Type*} [Preorder T] (α : RawAgent I T) : Prop :=
  ExtendedTime.finite α.birth < α.death

/-- Memory is local for a raw agent -/
def RawAgent.hasLocalMemory {I T : Type*} (α : RawAgent I T) : Prop :=
  ∀ t, α.memory t ⊆ α.localIdeas

/-- Memory is empty before birth for a raw agent -/
def RawAgent.hasEmptyPreBirthMemory {I T : Type*} [Preorder T] (α : RawAgent I T) : Prop :=
  ∀ t, t < α.birth → α.memory t = ∅

/-- Convert a RawAgent with proofs to an Agent -/
def RawAgent.toAgent {I T : Type*} [Preorder T] (α : RawAgent I T)
    (h1 : α.hasBirthBeforeDeath) (h2 : α.hasLocalMemory) (h3 : α.hasEmptyPreBirthMemory) :
    Agent I T where
  toRawAgent := α
  birth_before_death := h1
  memory_in_lifetime := h2
  memory_before_birth := h3

/-- Whether an agent is alive at a given time -/
def Agent.isAlive {I T : Type*} [Preorder T] (α : Agent I T) (t : T) : Prop :=
  α.birth ≤ t ∧ ExtendedTime.finite t < α.death

/-- An agent has perfect memory if they never forget anything -/
def Agent.hasPerfectMemory {I T : Type*} [Preorder T] (α : Agent I T) : Prop :=
  ∀ t₁ t₂, t₁ ≤ t₂ → α.isAlive t₁ → α.isAlive t₂ → α.memory t₁ ⊆ α.memory t₂

/-! ## Definition 2.2: Communication Channel

A channel from agent α to agent β is a function mapping an idea held by α 
at time t to the set of possible ideas received by β and the times of reception.
-/

/-- A raw communication channel between agents without delay constraints.
    This captures transmission, transformation/noise, and non-determinism.
    This is a more general structure that allows instantaneous or even backwards-in-time
    communication, which can model theoretical scenarios or approximations. -/
structure RawChannel (I₁ I₂ T : Type*) where
  /-- The transmission function: maps (idea, send_time) to set of (received_idea, receive_time) pairs -/
  transmit : I₁ × T → Set (I₂ × T)

/-- A communication channel between agents with positive delay.
    This captures transmission delay, transformation/noise, and non-determinism.
    Definition 2.2 from MULTI_AGENT_IDEOGENESIS++. -/
structure Channel (I₁ I₂ T : Type*) [Preorder T] extends RawChannel I₁ I₂ T where
  /-- Delay is positive: received time is after send time -/
  delay_positive : ∀ (a : I₁) (t₁ : T) (b : I₂) (t₂ : T),
    (b, t₂) ∈ transmit (a, t₁) → t₁ < t₂

/-- A channel has positive delay if all receptions happen after transmissions -/
def RawChannel.hasPositiveDelay {I₁ I₂ T : Type*} [Preorder T] (ch : RawChannel I₁ I₂ T) : Prop :=
  ∀ (a : I₁) (t₁ : T) (b : I₂) (t₂ : T), (b, t₂) ∈ ch.transmit (a, t₁) → t₁ < t₂

/-- Convert a RawChannel with positive delay proof to a Channel -/
def RawChannel.toChannel {I₁ I₂ T : Type*} [Preorder T] (ch : RawChannel I₁ I₂ T)
    (h : ch.hasPositiveDelay) : Channel I₁ I₂ T where
  transmit := ch.transmit
  delay_positive := h

/-- A channel is noisy if there exists a transmission where received ≠ sent.
    Definition 2.8 from MULTI_AGENT_IDEOGENESIS++. -/
def Channel.isNoisy {I₁ I₂ T : Type*} [Preorder T] (ch : Channel I₁ I₂ T) : Prop :=
  ∃ (a : I₁) (t₁ : T) (b : I₂) (t₂ : T), (b, t₂) ∈ ch.transmit (a, t₁)

/-- A channel is lossy if transmission can fail (produce no output).
    Definition 2.9 from MULTI_AGENT_IDEOGENESIS++. -/
def Channel.isLossy {I₁ I₂ T : Type*} [Preorder T] (ch : Channel I₁ I₂ T) : Prop :=
  ∃ (a : I₁) (t : T), ch.transmit (a, t) = ∅

/-- A channel has minimum delay δ.
    Definition 2.10 from MULTI_AGENT_IDEOGENESIS++. -/
def Channel.hasMinDelay {I₁ I₂ : Type*} (ch : Channel I₁ I₂ ℕ) (δ : ℕ) : Prop :=
  ∀ (a : I₁) (t₁ : ℕ) (b : I₂) (t₂ : ℕ),
    (b, t₂) ∈ ch.transmit (a, t₁) → t₂ ≥ t₁ + δ

/-- A channel is amplifying if a single transmission can produce multiple receptions.
    Definition 2.11 from MULTI_AGENT_IDEOGENESIS++. -/
def Channel.isAmplifying {I₁ I₂ T : Type*} [Preorder T] (ch : Channel I₁ I₂ T) : Prop :=
  ∃ (a : I₁) (t : T), (ch.transmit (a, t)).ncard > 1

/-- A channel is compressing if multiple ideas can map to the same received idea.
    Definition 2.12 from MULTI_AGENT_IDEOGENESIS++. -/
def Channel.isCompressing {I₁ I₂ T : Type*} [Preorder T] (ch : Channel I₁ I₂ T) : Prop :=
  ∃ (a₁ a₂ : I₁) (t : T), a₁ ≠ a₂ ∧ 
    (ch.transmit (a₁, t) ∩ ch.transmit (a₂, t)).Nonempty

/-! ## Definition 2.3: Multi-Agent Ideogenetic System (MAIS)

A MAIS is a tuple (A, I, gen, ch, ι, T) where:
- A is a set of agents
- I is the total idea space
- gen = {gen_α} is the family of generation operators
- ch = {ch_{α→β}} is the family of channels
- ι : A → Set I assigns primordial ideas to each agent
- T is the time structure
-/

/-- A raw multi-agent ideogenetic system without structural constraints.
    This is a minimal structure that allows maximum flexibility in modeling.
    Use MAIS for systems with standard well-formedness conditions. -/
structure RawMAIS (I : Type*) (T : Type*) [Preorder T] where
  /-- The set of agents in the system -/
  agents : Set (Agent I T)
  /-- Communication channels between agents -/
  channel : Agent I T → Agent I T → Channel I I T
  /-- Primordial ideas assigned to each agent -/
  primordials : Agent I T → Set I

/-- A multi-agent ideogenetic system with standard well-formedness conditions.
    Definition 2.3 from MULTI_AGENT_IDEOGENESIS++. -/
structure MAIS (I : Type*) (T : Type*) [Preorder T] extends RawMAIS I T where
  /-- Agents have distinct identifiers -/
  agents_distinct : ∀ α ∈ agents, ∀ β ∈ agents, α.agentId = β.agentId → α = β
  /-- Primordials are in the agent's local space -/
  primordials_local : ∀ α ∈ agents, primordials α ⊆ α.localIdeas
  /-- Primordials are in initial memory -/
  primordials_in_memory : ∀ α ∈ agents, primordials α ⊆ α.memory α.birth

/-- Agents in a RawMAIS have distinct identifiers -/
def RawMAIS.hasDistinctAgents {I T : Type*} [Preorder T] (M : RawMAIS I T) : Prop :=
  ∀ α ∈ M.agents, ∀ β ∈ M.agents, α.agentId = β.agentId → α = β

/-- Primordials are local in a RawMAIS -/
def RawMAIS.hasLocalPrimordials {I T : Type*} [Preorder T] (M : RawMAIS I T) : Prop :=
  ∀ α ∈ M.agents, M.primordials α ⊆ α.localIdeas

/-- Primordials are in initial memory in a RawMAIS -/
def RawMAIS.hasPrimordialsInMemory {I T : Type*} [Preorder T] (M : RawMAIS I T) : Prop :=
  ∀ α ∈ M.agents, M.primordials α ⊆ α.memory α.birth

/-- Convert a RawMAIS with proofs to a MAIS -/
def RawMAIS.toMAIS {I T : Type*} [Preorder T] (M : RawMAIS I T)
    (h1 : M.hasDistinctAgents) (h2 : M.hasLocalPrimordials) (h3 : M.hasPrimordialsInMemory) :
    MAIS I T where
  toRawMAIS := M
  agents_distinct := h1
  primordials_local := h2
  primordials_in_memory := h3

/-! ## Definition 2.4: Collective State

The collective state at time t is the set of all (agent, idea) pairs at that time.
These definitions work on RawMAIS for maximum generality.
-/

/-- The collective state at time t: all (agent, idea) pairs held by living agents.
    Definition 2.4 from MULTI_AGENT_IDEOGENESIS++.
    Works on RawMAIS for maximum generality. -/
def RawMAIS.collectiveState {I T : Type*} [Preorder T] (M : RawMAIS I T) (t : T) :
    Set (Agent I T × I) :=
  { pair | pair.1 ∈ M.agents ∧ pair.1.isAlive t ∧ pair.2 ∈ pair.1.memory t }

/-- The set of all ideas held by at least one agent at time t.
    Works on RawMAIS for maximum generality. -/
def RawMAIS.heldIdeas {I T : Type*} [Preorder T] (M : RawMAIS I T) (t : T) : Set I :=
  { a | ∃ α ∈ M.agents, α.isAlive t ∧ a ∈ α.memory t }

/-- The set of all living agents at time t.
    Works on RawMAIS for maximum generality. -/
def RawMAIS.livingAgents {I T : Type*} [Preorder T] (M : RawMAIS I T) (t : T) :
    Set (Agent I T) :=
  { α ∈ M.agents | α.isAlive t }

/-- Alias for MAIS using RawMAIS definitions -/
abbrev MAIS.collectiveState {I T : Type*} [Preorder T] (M : MAIS I T) (t : T) :
    Set (Agent I T × I) := M.toRawMAIS.collectiveState t

/-- Alias for MAIS using RawMAIS definitions -/
abbrev MAIS.heldIdeas {I T : Type*} [Preorder T] (M : MAIS I T) (t : T) : Set I :=
  M.toRawMAIS.heldIdeas t

/-- Alias for MAIS using RawMAIS definitions -/
abbrev MAIS.livingAgents {I T : Type*} [Preorder T] (M : MAIS I T) (t : T) :
    Set (Agent I T) := M.toRawMAIS.livingAgents t

/-! ## Definition 2.5: State Transition (simplified for now)

The full dynamics are complex, involving:
1. Generation: Each agent applies gen_α to ideas in mem_α(t)
2. Communication: Ideas flow through channels
3. Memory update: Each agent updates their memory

For now, we define the basic structure; full dynamics will be in Dynamics.lean.
-/

/-- The ideas received by an agent at time t through all channels.
    Part of Definition 2.5 from MULTI_AGENT_IDEOGENESIS++.
    Works on RawMAIS for maximum generality. -/
def RawMAIS.receivedAt {I T : Type*} [Preorder T]
    (M : RawMAIS I T) (α : Agent I T) (t : T) : Set I :=
  { b | ∃ β ∈ M.agents, ∃ a ∈ β.memory t, ∃ t' : T, t' < t ∧
        (b, t) ∈ (M.channel β α).transmit (a, t') }

/-- Alias for MAIS using RawMAIS definitions -/
abbrev MAIS.receivedAt {I T : Type*} [Preorder T]
    (M : MAIS I T) (α : Agent I T) (t : T) : Set I := M.toRawMAIS.receivedAt α t

/-- The ideas generated by an agent at time t from their current memory -/
def Agent.generatedAt {I T : Type*} [Preorder T] 
    (α : Agent I T) (t : T) : Set I :=
  ⋃ a ∈ α.memory t, α.generate a

/-! ## Definition 2.6: Forgetting Function

A forgetting function models memory limitations.
An agent with perfect memory has forget_α(t) = ∅ for all t.
-/

/-- A forgetting function specifies what an agent forgets at each time step.
    Definition 2.6 from MULTI_AGENT_IDEOGENESIS++. -/
structure ForgettingFunction (I T : Type*) where
  /-- The function mapping time to the set of ideas forgotten at that time -/
  forget : T → Set I

/-! ## Definition 2.26: Generative Familiarity

An agent is familiar with an idea if they have encountered it through memory or reception.
This is a weak cognitive constraint: one cannot reason productively about ideas never encountered.
-/

/-- An agent is familiar with idea a at time t if a has been in their memory at some point,
    or has been received through a channel. This captures the cognitive constraint that
    generation requires prior exposure.
    Definition 2.26 from MULTI_AGENT_IDEOGENESIS++.
    Works on RawMAIS for maximum generality. -/
def RawMAIS.isFamiliar {I : Type*} (M : RawMAIS I ℕ) (α : Agent I ℕ) (a : I) (t : ℕ) : Prop :=
  -- Either the agent has held the idea at some point
  (∃ t' ≤ t, a ∈ α.memory t') ∨
  -- Or the agent has received the idea through a channel
  (∃ β ∈ M.agents, ∃ t' < t, ∃ b, (a, t') ∈ (M.channel β α).transmit (b, t' - 1))

/-- Alias for MAIS using RawMAIS definitions -/
abbrev MAIS.isFamiliar {I : Type*} (M : MAIS I ℕ) (α : Agent I ℕ) (a : I) (t : ℕ) : Prop :=
  M.toRawMAIS.isFamiliar α a t

/-- Under isolation (trivial incoming channels), an agent is only familiar
    with ideas they have held in their own memory.
    Note: We only require channels *to* α are trivial, not all channels in the system.
    Works on RawMAIS for maximum generality. -/
theorem RawMAIS.familiar_under_isolation {I : Type*} (M : RawMAIS I ℕ) (α : Agent I ℕ) (a : I) (t : ℕ)
    (htriv : ∀ β : Agent I ℕ, (M.channel β α).transmit = fun _ => ∅)
    (hfam : M.isFamiliar α a t) :
    ∃ t' ≤ t, a ∈ α.memory t' := by
  cases hfam with
  | inl h => exact h
  | inr h =>
    obtain ⟨β, hβ, t', ht', b, hrecv⟩ := h
    simp only [htriv, Set.mem_empty_iff_false] at hrecv

/-- Alias for MAIS using RawMAIS theorem -/
theorem MAIS.familiar_under_isolation {I : Type*} (M : MAIS I ℕ) (α : Agent I ℕ) (a : I) (t : ℕ)
    (htriv : ∀ β : Agent I ℕ, (M.channel β α).transmit = fun _ => ∅)
    (hfam : M.isFamiliar α a t) :
    ∃ t' ≤ t, a ∈ α.memory t' := RawMAIS.familiar_under_isolation M.toRawMAIS α a t htriv hfam

/-! ## Basic Properties of MAIS

These properties work on RawMAIS for maximum generality.
-/

/-- A RawMAIS is finite if it has finitely many agents -/
def RawMAIS.isFinite {I T : Type*} [Preorder T] (M : RawMAIS I T) : Prop :=
  M.agents.Finite

/-- A RawMAIS is immortal if all agents live forever -/
def RawMAIS.isImmortal {I T : Type*} [Preorder T] (M : RawMAIS I T) : Prop :=
  ∀ α ∈ M.agents, α.death = ExtendedTime.infinite

/-- A RawMAIS has perfect memory if all agents have perfect memory -/
def RawMAIS.hasPerfectMemory {I T : Type*} [Preorder T] (M : RawMAIS I T) : Prop :=
  ∀ α ∈ M.agents, α.hasPerfectMemory

/-- The total number of ideas currently in the system -/
noncomputable def RawMAIS.totalIdeas {I T : Type*} [Preorder T] (M : RawMAIS I T) (t : T) : ℕ :=
  (M.heldIdeas t).ncard

/-- Alias for MAIS -/
abbrev MAIS.isFinite {I T : Type*} [Preorder T] (M : MAIS I T) : Prop := M.toRawMAIS.isFinite

/-- Alias for MAIS -/
abbrev MAIS.isImmortal {I T : Type*} [Preorder T] (M : MAIS I T) : Prop := M.toRawMAIS.isImmortal

/-- Alias for MAIS -/
abbrev MAIS.hasPerfectMemory {I T : Type*} [Preorder T] (M : MAIS I T) : Prop :=
  M.toRawMAIS.hasPerfectMemory

/-- Alias for MAIS -/
noncomputable abbrev MAIS.totalIdeas {I T : Type*} [Preorder T] (M : MAIS I T) (t : T) : ℕ :=
  M.toRawMAIS.totalIdeas t

/-! ## Single-Agent Embedding (Theorem 16.1)

Every single-agent ideogenetic system embeds into a multi-agent system 
with one agent and trivial channels.
-/

/-- Convert a single-agent system to a raw agent in the multi-agent framework -/
def singleAgentToRawAgent (S : IdeogeneticSystem) : RawAgent S.Idea ℕ where
  agentId := ⟨0⟩
  localIdeas := Set.univ
  generate := S.generate
  memory := fun t => genCumulative S t {S.primordial}
  birth := 0
  death := ExtendedTime.infinite

/-- Convert a single-agent system to an immortal agent in the multi-agent framework -/
def singleAgentToAgent (S : IdeogeneticSystem) : Agent S.Idea ℕ where
  toRawAgent := singleAgentToRawAgent S
  birth_before_death := ExtendedTime.finite_lt_infinite 0
  memory_in_lifetime := fun _ => Set.subset_univ _
  memory_before_birth := fun t ht => by
    simp only [singleAgentToRawAgent]
    have : t < 0 := ht
    omega

/-- The trivial raw channel that never transmits -/
def trivialRawChannel (I T : Type*) : RawChannel I I T where
  transmit := fun _ => ∅

/-- The trivial channel that never transmits (for self-communication in single-agent case) -/
def trivialChannel (I : Type*) : Channel I I ℕ where
  transmit := fun _ => ∅
  delay_positive := fun _ _ _ _ h => by simp at h

/-- Embed a single-agent system into a RawMAIS (without well-formedness constraints) -/
def singleAgentToRawMAIS (S : IdeogeneticSystem) : RawMAIS S.Idea ℕ where
  agents := {singleAgentToAgent S}
  channel := fun _ _ => trivialChannel S.Idea
  primordials := fun _ => {S.primordial}

/-- Embed a single-agent system into a MAIS -/
def singleAgentToMAIS (S : IdeogeneticSystem) : MAIS S.Idea ℕ where
  toRawMAIS := singleAgentToRawMAIS S
  agents_distinct := fun α hα β hβ _ => by
    have hα' : α ∈ ({singleAgentToAgent S} : Set (Agent S.Idea ℕ)) := hα
    have hβ' : β ∈ ({singleAgentToAgent S} : Set (Agent S.Idea ℕ)) := hβ
    simp only [Set.mem_singleton_iff] at hα' hβ'
    rw [hα', hβ']
  primordials_local := fun α hα => by
    have hα' : α ∈ ({singleAgentToAgent S} : Set (Agent S.Idea ℕ)) := hα
    simp only [Set.mem_singleton_iff] at hα'
    subst hα'
    exact Set.subset_univ _
  primordials_in_memory := fun α hα => by
    have hα' : α ∈ ({singleAgentToAgent S} : Set (Agent S.Idea ℕ)) := hα
    simp only [Set.mem_singleton_iff] at hα'
    subst hα'
    intro x hx
    have hx' : x ∈ ({S.primordial} : Set S.Idea) := hx
    simp only [Set.mem_singleton_iff] at hx'
    subst hx'
    simp only [singleAgentToAgent, singleAgentToRawAgent, genCumulative, Set.mem_singleton_iff]

/-- The embedded single-agent closure equals the RawMAIS closure at any time
    (Theorem 16.1 from MULTI_AGENT_IDEOGENESIS++, generalized to RawMAIS) -/
theorem single_agent_embedding_closure_raw (S : IdeogeneticSystem) (t : ℕ) :
    (singleAgentToRawMAIS S).heldIdeas t = genCumulative S t {S.primordial} := by
  ext a
  simp only [RawMAIS.heldIdeas, singleAgentToRawMAIS, Set.mem_singleton_iff,
             singleAgentToAgent, Set.mem_setOf_eq]
  constructor
  · intro ⟨α, hα, halive, ha⟩
    subst hα
    exact ha
  · intro ha
    refine ⟨singleAgentToAgent S, rfl, ?_, ha⟩
    simp only [Agent.isAlive, singleAgentToAgent]
    exact ⟨Nat.zero_le t, ExtendedTime.finite_lt_infinite t⟩

/-- The embedded single-agent closure equals the MAIS closure at any time
    (Theorem 16.1 from MULTI_AGENT_IDEOGENESIS++) -/
theorem single_agent_embedding_closure (S : IdeogeneticSystem) (t : ℕ) :
    (singleAgentToMAIS S).heldIdeas t = genCumulative S t {S.primordial} :=
  single_agent_embedding_closure_raw S t

end CollectiveIdeogenesis
