/-
AUTO-AUDIT 2026-02-08
Current assumptions summary:
- Theorems in this file use explicit binder hypotheses/typeclass assumptions in their signatures.
- Global `axiom` declarations: none.
- `sorry`/`admit` occurrences: none.
Potential weakening targets:
- No non-derivable assumptions were found beyond explicit theorem hypotheses.
-/

/-
# Collective Ideogenesis: Novelty in Multi-Agent Systems

This file contains definitions and theorems about novelty in multi-agent systems
from MULTI_AGENT_IDEOGENESIS++ Chapter 4:

- Definition 4.1: Individual Novelty
- Definition 4.2: Collective Novelty
- Definition 4.3: Generator
- Definition 4.4: Co-Generation
- Theorem 4.1: Collective Novelty Exceeds Individual Sum
- Definition 4.5-4.6: Combinatorial Novelty
- Theorem 4.2: Communication Increases Combinatorial Novelty
- Definition 4.7-4.8: Redundancy
- Theorem 4.3: Redundancy-Resilience
-/

import Mathlib.Data.Set.Basic
import Mathlib.Data.Set.Card
import Mathlib.Data.Nat.Defs
import Mathlib.Order.Basic
import Mathlib.Tactic
import FormalAnthropology.Collective_Basic
import FormalAnthropology.Collective_Closure

namespace CollectiveIdeogenesis

/-! ## Definition 4.1: Individual Novelty

Idea a is individually novel to agent α at time t if α holds a at t 
but did not hold a before t.
-/

/-- An idea is individually novel to an agent at time t if they just acquired it.
    Definition 4.1 from MULTI_AGENT_IDEOGENESIS++. -/
def Agent.isNovelAt {I : Type*} (α : Agent I ℕ) (a : I) (t : ℕ) : Prop :=
  a ∈ α.memory t ∧ ∀ t' < t, a ∉ α.memory t'

/-- The set of individually novel ideas for an agent at time t -/
def Agent.novelIdeas {I : Type*} (α : Agent I ℕ) (t : ℕ) : Set I :=
  { a | α.isNovelAt a t }

/-- An agent's novelty count at time t -/
noncomputable def Agent.noveltyCount {I : Type*} (α : Agent I ℕ) (t : ℕ) : ℕ :=
  (α.novelIdeas t).ncard

/-! ## Definition 4.2: Collective Novelty

Idea a is collectively novel at time t if no agent has ever held a before t.
-/

/-- An idea is collectively novel if it appears for the first time in the system.
    Definition 4.2 from MULTI_AGENT_IDEOGENESIS++. -/
def MAIS.isCollectivelyNovel {I : Type*} (M : MAIS I ℕ) (a : I) (t : ℕ) : Prop :=
  (∃ α ∈ M.agents, a ∈ α.memory t) ∧ 
  ∀ t' < t, ∀ β ∈ M.agents, a ∉ β.memory t'

/-- The set of collectively novel ideas at time t -/
def MAIS.collectivelyNovelIdeas {I : Type*} (M : MAIS I ℕ) (t : ℕ) : Set I :=
  { a | M.isCollectivelyNovel a t }

/-- The collective novelty count at time t -/
noncomputable def MAIS.collectiveNoveltyCount {I : Type*} (M : MAIS I ℕ) (t : ℕ) : ℕ :=
  (M.collectivelyNovelIdeas t).ncard

/-! ## Definition 4.3: Generator

Agent α is the generator of collectively novel idea a if a is collectively 
novel at t and α holds a at t.
-/

/-- Agent α is a generator of idea a at time t.
    Definition 4.3 from MULTI_AGENT_IDEOGENESIS++. -/
def MAIS.isGenerator {I : Type*} (M : MAIS I ℕ) (α : Agent I ℕ) (a : I) (t : ℕ) : Prop :=
  α ∈ M.agents ∧ M.isCollectivelyNovel a t ∧ a ∈ α.memory t

/-- The set of generators at time t (agent-idea pairs) -/
def MAIS.generators {I : Type*} (M : MAIS I ℕ) (t : ℕ) : Set (Agent I ℕ × I) :=
  { pair | M.isGenerator pair.1 pair.2 t }

/-! ## Definition 4.4: Co-Generation

Ideas that emerge from collective interaction and couldn't be generated by 
any single agent alone.
-/

/-- An idea is co-generated if multiple agents contributed to its generation.
    Definition 4.4 from MULTI_AGENT_IDEOGENESIS++.
    a is co-generated at t if:
    - a first appears at time t
    - a is not in any single agent's local generation from their memory at t-1
    - a emerges from combining ideas across multiple agents -/
def MAIS.isCoGenerated {I : Type*} (M : MAIS I ℕ) (a : I) (t : ℕ) : Prop :=
  M.isCollectivelyNovel a t ∧
  (∀ α ∈ M.agents, a ∉ ⋃ b ∈ α.memory (t - 1), α.generate b) ∧
  t > 0

/-- The set of co-generated ideas at time t -/
def MAIS.coGeneratedIdeas {I : Type*} (M : MAIS I ℕ) (t : ℕ) : Set I :=
  { a | M.isCoGenerated a t }

/-! ## Theorem 4.1: Collective Novelty Exceeds Individual Sum

There exist multi-agent systems where collective novelty exceeds the sum 
of individual novelties.
-/

/-- Sum of individual novelty counts across all agents (requires finite agents) -/
noncomputable def MAIS.sumIndividualNovelty {I : Type*} (M : MAIS I ℕ) (t : ℕ) 
    (hfin : M.isFinite) : ℕ :=
  ∑ α ∈ hfin.toFinset, α.noveltyCount t

/-- Collectively novel ideas that are not individually novel to anyone.
    These are ideas that emerge through collective interaction. -/
def MAIS.purelyCollectiveNovelty {I : Type*} (M : MAIS I ℕ) (t : ℕ) : Set I :=
  { a | M.isCollectivelyNovel a t ∧ ∀ α ∈ M.agents, ¬α.isNovelAt a t }

/-- If there are purely collective novel ideas, the set is nonempty.
    This is part of Theorem 4.1 from MULTI_AGENT_IDEOGENESIS++. -/
theorem MAIS.collective_exceeds_individual {I : Type*} (M : MAIS I ℕ) (t : ℕ)
    (hfinite : M.isFinite)
    (hfin_mem : ∀ α ∈ M.agents, (α.memory t).Finite)
    (hpure : (M.purelyCollectiveNovelty t).Nonempty) :
    (M.purelyCollectiveNovelty t).ncard > 0 := by
  -- purelyCollectiveNovelty is a subset of collectivelyNovelIdeas
  have hsub : M.purelyCollectiveNovelty t ⊆ M.collectivelyNovelIdeas t := 
    fun a ha => ha.1
  -- collectivelyNovelIdeas at t is finite (subset of held ideas which is bounded by agents)
  have hfin_novel : (M.collectivelyNovelIdeas t).Finite := by
    -- collectivelyNovelIdeas = { a | isCollectivelyNovel a t }
    -- isCollectivelyNovel a t = (∃ α ∈ M.agents, a ∈ α.memory t) ∧ (∀ t' < t, ∀ β ∈ M.agents, a ∉ β.memory t')
    -- So collectivelyNovelIdeas ⊆ { a | ∃ α ∈ M.agents, a ∈ α.memory t }
    have hsub1 : M.collectivelyNovelIdeas t ⊆ { a | ∃ α ∈ M.agents, a ∈ α.memory t } := by
      intro a ha
      simp only [collectivelyNovelIdeas, Set.mem_setOf_eq, isCollectivelyNovel] at ha
      exact ha.1
    apply Set.Finite.subset _ hsub1
    -- { a | ∃ α ∈ M.agents, a ∈ α.memory t } ⊆ ⋃ α ∈ M.agents, α.memory t
    have hsub2 : { a | ∃ α ∈ M.agents, a ∈ α.memory t } ⊆ ⋃ α ∈ M.agents, α.memory t := by
      intro a ⟨α, hα, ha⟩
      simp only [Set.mem_iUnion]
      exact ⟨α, hα, ha⟩
    apply Set.Finite.subset _ hsub2
    exact Set.Finite.biUnion hfinite hfin_mem
  have hfin_pure : (M.purelyCollectiveNovelty t).Finite := Set.Finite.subset hfin_novel hsub
  exact Set.ncard_pos hfin_pure |>.mpr hpure

/-! ## Definition 4.5-4.6: Combinatorial Novelty

Ideas created by combining insights from different agents.
For γ to generate c from combining ideas a and b (i.e., gen_γ({a,b})),
γ must hold both a and b in memory at the time of generation.
-/

/-- An idea is combinatorially novel if it arises from combining ideas from different agents
    who don't share those source ideas. The generator γ holds both a and b at time t-1
    (enabling generation from the set {a,b}), where a originated from α and b from β.
    Definition 4.5 from MULTI_AGENT_IDEOGENESIS++. -/
def MAIS.isCombinatoriallyNovel {I : Type*} (M : MAIS I ℕ) (c : I) (t : ℕ) : Prop :=
  M.isCollectivelyNovel c t ∧
  ∃ (α β : Agent I ℕ) (a b : I) (γ : Agent I ℕ),
    α ∈ M.agents ∧ β ∈ M.agents ∧ γ ∈ M.agents ∧
    α ≠ β ∧
    -- a is held by α but not β; b is held by β but not α (at t-1)
    a ∈ α.memory (t - 1) ∧ b ∈ β.memory (t - 1) ∧
    a ∉ β.memory (t - 1) ∧ b ∉ α.memory (t - 1) ∧
    -- γ holds both a and b at t-1, enabling generation from {a,b}
    a ∈ γ.memory (t - 1) ∧ b ∈ γ.memory (t - 1) ∧
    -- c is generated by γ from a or b
    c ∈ γ.generate a ∪ γ.generate b

/-- The set of combinatorially novel ideas at time t -/
def MAIS.combinatoriallyNovelIdeas {I : Type*} (M : MAIS I ℕ) (t : ℕ) : Set I :=
  { c | M.isCombinatoriallyNovel c t }

/-- The combinatorial novelty rate: count of combinatorial ideas at time t.
    Definition 4.6 from MULTI_AGENT_IDEOGENESIS++. -/
noncomputable def MAIS.combinatorialNoveltyRate {I : Type*} (M : MAIS I ℕ) (t : ℕ) : ℕ :=
  (M.combinatoriallyNovelIdeas t).ncard

/-! ## Theorem 4.2: Communication Enables Combinatorial Novelty

Systems with higher channel capacity have higher combinatorial novelty rates.
We formalize a structural property: combinatorial novelty requires communication.
-/

/-- If agents have disjoint memories at each time (no shared ideas without communication),
    then combinatorial novelty is impossible.
    This is Theorem 4.2 from MULTI_AGENT_IDEOGENESIS++.
    
    The proof: For combinatorial novelty, we need γ to hold both a and b at t-1,
    where a is in α's memory and b is in β's memory with α ≠ β.
    Under per-time isolation, a ∈ γ.memory (t-1) and a ∈ α.memory (t-1) implies γ = α.
    Similarly for b. But then γ = α = β, contradicting α ≠ β. -/
theorem MAIS.no_communication_no_combinatorial {I : Type*} (M : MAIS I ℕ) (t : ℕ)
    (hisolated : ∀ α ∈ M.agents, ∀ β ∈ M.agents, α ≠ β → 
      ∀ a, a ∈ α.memory (t - 1) → a ∉ β.memory (t - 1)) :
    M.combinatoriallyNovelIdeas t = ∅ := by
  ext c
  simp only [combinatoriallyNovelIdeas, Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
  intro ⟨_, α, β, a, b, γ, hα, hβ, hγ, hne, ha, hb, _, hba, ha_γ, hb_γ, _⟩
  -- a ∈ α.memory (t-1) and a ∈ γ.memory (t-1)
  -- If α ≠ γ, then by isolation: a ∈ α.memory (t-1) → a ∉ γ.memory (t-1)
  -- This contradicts ha_γ. So γ = α.
  have hγα : γ = α := by
    by_contra hne'
    exact hisolated α hα γ hγ (Ne.symm hne') a ha ha_γ
  -- Similarly, b ∈ β.memory (t-1) and b ∈ γ.memory (t-1)
  -- If β ≠ γ, then by isolation: b ∈ β.memory (t-1) → b ∉ γ.memory (t-1)
  -- This contradicts hb_γ. So γ = β.
  have hγβ : γ = β := by
    by_contra hne'
    exact hisolated β hβ γ hγ (Ne.symm hne') b hb hb_γ
  -- But γ = α and γ = β implies α = β, contradicting hne : α ≠ β
  exact hne (hγα.symm.trans hγβ)

/-! ## Definition 4.7-4.8: Redundancy

Measures how many agents can generate or hold an idea.
-/

/-- The generation redundancy of idea a at time t: how many agents could generate a.
    Definition 4.7 from MULTI_AGENT_IDEOGENESIS++. -/
noncomputable def MAIS.generationRedundancy {I : Type*} (M : MAIS I ℕ) (a : I) (t : ℕ) : ℕ :=
  { α ∈ M.agents | ∃ b ∈ α.memory t, a ∈ α.generate b }.ncard

/-- The holding redundancy of idea a at time t: how many agents hold a.
    Related to Definition 4.8 from MULTI_AGENT_IDEOGENESIS++. -/
noncomputable def MAIS.holdingRedundancy {I : Type*} (M : MAIS I ℕ) (a : I) (t : ℕ) : ℕ :=
  { α ∈ M.agents | a ∈ α.memory t }.ncard

/-- Holding redundancy relates to the holders count from Closure.lean.
    Note: holdingRedundancy counts all agents, while holdersCount counts living agents.
    These are equal when all agents are alive. -/
theorem MAIS.holdingRedundancy_eq_holdersCount {I : Type*} (M : MAIS I ℕ) (a : I) (t : ℕ)
    (hall_alive : ∀ α ∈ M.agents, α.isAlive t) :
    M.holdingRedundancy a t = { α ∈ M.livingAgents t | a ∈ α.memory t }.ncard := by
  -- Under the assumption all agents are alive, the sets are equal
  -- Show the sets themselves are equal, then ncard is equal
  have heq : { α ∈ M.agents | a ∈ α.memory t } = { α ∈ M.livingAgents t | a ∈ α.memory t } := by
    ext α
    simp only [Set.mem_sep_iff, livingAgents, Set.mem_sep_iff]
    constructor
    · intro ⟨hα, ha⟩
      exact ⟨⟨hα, hall_alive α hα⟩, ha⟩
    · intro ⟨⟨hα, _⟩, ha⟩
      exact ⟨hα, ha⟩
  simp only [holdingRedundancy, heq]

/-! ## Theorem 4.3: Redundancy-Resilience

High redundancy implies resilience to agent loss.
-/

/-- An idea survives agent loss if someone other than the lost agent holds it.
    Part of Theorem 4.3 from MULTI_AGENT_IDEOGENESIS++. -/
def MAIS.survivesLoss {I : Type*} (M : MAIS I ℕ) (a : I) (α : Agent I ℕ) (t : ℕ) : Prop :=
  ∃ β ∈ M.agents, β ≠ α ∧ a ∈ β.memory t

/-- If redundancy ≥ 2, the idea survives loss of any single agent.
    This is Theorem 4.3 from MULTI_AGENT_IDEOGENESIS++. -/
theorem MAIS.redundancy_implies_resilience {I : Type*} (M : MAIS I ℕ) (a : I) (t : ℕ)
    (hfinite : M.isFinite)
    (hred : M.holdingRedundancy a t ≥ 2) (α : Agent I ℕ) (hα : α ∈ M.agents) 
    (ha : a ∈ α.memory t) :
    M.survivesLoss a α t := by
  -- If ≥2 agents hold a, then there's another agent besides α who holds it
  have hcard : { β ∈ M.agents | a ∈ β.memory t }.ncard ≥ 2 := hred
  have hnonempty : { β ∈ M.agents | a ∈ β.memory t }.Nonempty := by
    use α
    exact ⟨hα, ha⟩
  -- With cardinality ≥ 2, there must be at least 2 distinct elements
  have hfin : { β ∈ M.agents | a ∈ β.memory t }.Finite := 
    Set.Finite.subset hfinite (fun β hβ => hβ.1)
  -- If removing α still leaves nonempty set, we're done
  have hdiff : ({ β ∈ M.agents | a ∈ β.memory t } \ {α}).Nonempty := by
    by_contra hemp
    rw [Set.not_nonempty_iff_eq_empty, Set.diff_eq_empty] at hemp
    -- All holders are α, so there's only 1 holder
    have hsub : { β ∈ M.agents | a ∈ β.memory t } ⊆ {α} := hemp
    have hle : { β ∈ M.agents | a ∈ β.memory t }.ncard ≤ ({α} : Set (Agent I ℕ)).ncard := 
      Set.ncard_le_ncard hsub (Set.finite_singleton α)
    rw [Set.ncard_singleton] at hle
    omega
  obtain ⟨β, hβ⟩ := hdiff
  simp only [Set.mem_diff, Set.mem_sep_iff, Set.mem_singleton_iff] at hβ
  exact ⟨β, hβ.1.1, hβ.2, hβ.1.2⟩

/-! ## Additional Novelty Properties -/

/-- Novelty is monotone: once generated, an idea was novel at its first appearance.
    This theorem requires that agents have empty memory when not alive,
    which is a natural constraint in the MAIS framework. -/
theorem MAIS.novelty_first_appearance {I : Type*} (M : MAIS I ℕ) (a : I) (t : ℕ)
    (h : a ∈ M.heldIdeas t)
    (hmem_lifetime : ∀ α ∈ M.agents, ∀ s, ¬α.isAlive s → α.memory s = ∅) :
    ∃ t₀ ≤ t, M.isCollectivelyNovel a t₀ := by
  -- There exists a first time when a appeared
  have hex : ∃ s, a ∈ M.heldIdeas s := ⟨t, h⟩
  -- Define t₀ as the first appearance time
  let t₀ := @Nat.find (fun k => a ∈ M.heldIdeas k) (Classical.decPred _) hex
  use t₀
  constructor
  · -- t₀ ≤ t
    exact @Nat.find_le t (fun k => a ∈ M.heldIdeas k) (Classical.decPred _) hex h
  · -- a is collectively novel at t₀
    constructor
    · -- Someone holds a at t₀: unpack heldIdeas
      have hspec := @Nat.find_spec (fun k => a ∈ M.heldIdeas k) (Classical.decPred _) hex
      simp only [heldIdeas, Set.mem_setOf_eq] at hspec
      obtain ⟨α, hα, _, hmem⟩ := hspec
      exact ⟨α, hα, hmem⟩
    · -- No one held a before t₀
      intro t' ht' β hβ ha_in_mem
      have hmin := @Nat.find_min (fun k => a ∈ M.heldIdeas k) (Classical.decPred _) hex t' ht'
      simp only [heldIdeas, Set.mem_setOf_eq, not_exists] at hmin
      -- hmin : ¬∃ α ∈ M.agents, α.isAlive t' ∧ a ∈ α.memory t'
      exfalso
      apply hmin
      by_cases hβalive : β.isAlive t'
      · exact ⟨β, hβ, hβalive, ha_in_mem⟩
      · -- β not alive at t', so β.memory t' = ∅ by hmem_lifetime
        have hempty := hmem_lifetime β hβ t' hβalive
        rw [hempty] at ha_in_mem
        exact absurd ha_in_mem (Set.not_mem_empty a)

end CollectiveIdeogenesis
