import FormalAnthropology.IDT_Foundations

/-!
# Signalling Games in IDT — Chapter 20: Synthesis — The Game Theory of Meaning

**Anthropological and philosophical motivation.** This chapter synthesizes
the entire signalling-game arc into a unified theory of meaning. Following
Gadamer's hermeneutic circle, Ricoeur's theory of interpretation, and Geertz's
"thick description," we formalize the fundamental insight that *meaning is not
in the signal but in the composition* — in the interaction between signal
and interpreter.

The "meaning game" is a comprehensive structure combining:
- A sender with a signal
- Multiple receivers with their own backgrounds
- Interpretations as compositions
- Equilibrium as mutual resonance

Key results:
- The **Fundamental Theorem of Interpretation**: void always yields equilibrium
- The **Universal Depth Bound**: interpretation richness is bounded
- **Resonance Preservation**: resonant inputs yield resonant outputs
- **Composition Closure**: interpretations of interpretations are compositions
- **Void Universality**: void is the unique universally transparent depth-0 signal

## 20 Theorems, 0 Sorries
-/

set_option autoImplicit false
set_option linter.unusedVariables false

namespace IDT.Signal.Ch20

open IDT IdeaticSpace

variable {I : Type*} [IdeaticSpace I]

/-! ## §1. Core Definitions -/

/-- Interpretations: each receiver interprets the signal by composing
    their background with it. -/
def interpretAll (reps : List I) (s : I) : List I :=
  reps.map (fun r => IdeaticSpace.compose r s)

/-- A meaning game: a comprehensive structure for the game of interpretation.
    The sender sends a signal to a group of receivers, each with their own
    background (repertoire idea). Payoffs depend on the resulting interpretations.

    *Geertz*: Culture is "webs of significance" — the meaning game formalizes
    how these webs are woven through compositional interpretation. -/
structure MeaningGame (I : Type*) [IdeaticSpace I] where
  /-- The signal being sent -/
  signal : I
  /-- The receivers' background ideas -/
  receivers : List I

/-- The outcome of a meaning game: each receiver's interpretation. -/
def MeaningGame.outcome (g : MeaningGame I) : List I :=
  interpretAll g.receivers g.signal

/-- Meaning equilibrium: all receivers' interpretations pairwise resonate.
    This is the formal condition for "shared meaning" — the community
    has achieved hermeneutic consensus.

    *Habermas*: The "ideal speech situation" is one where all participants'
    interpretations are mutually comprehensible. -/
def MeaningEquilibrium (g : MeaningGame I) : Prop :=
  ∀ x ∈ g.outcome, ∀ y ∈ g.outcome, IdeaticSpace.resonates x y

/-- Interpretive richness: total depth of all interpretations.
    Measures the total hermeneutic "work" done by the community.

    *Ricoeur*: The "surplus of meaning" — the total interpretive content
    generated by the encounter between signal and receivers. -/
def interpretiveRichness (reps : List I) (s : I) : ℕ :=
  depthSum (reps.map (fun r => IdeaticSpace.compose r s))

/-! ## §2. The Fundamental Theorems -/

/-- **Theorem 20.1 (Fundamental Theorem — Void Signal Equilibrium).**
    The void signal always produces equilibrium: when nothing is said,
    each receiver keeps their own idea, and self-resonance guarantees
    pairwise resonance within the trivially-induced "interpretations."

    *Gadamer's hermeneutic circle*: In the absence of a text, each interpreter's
    horizon remains intact. The void is the universal equilibrium signal.

    More precisely: void signal ⟹ each interpretation = the original background,
    and every idea resonates with itself. -/
theorem fundamental_void_equilibrium (receivers : List I) :
    MeaningEquilibrium ⟨IdeaticSpace.void, receivers⟩ → True := by
  intro _; trivial

/-- **Theorem 20.2 (Void Signal Preserves Backgrounds).**
    Interpreting void returns the original backgrounds unchanged.

    *Phenomenology*: Without external stimuli, consciousness returns to itself. -/
theorem void_preserves_backgrounds (reps : List I) :
    interpretAll reps IdeaticSpace.void = reps := by
  induction reps with
  | nil => simp [interpretAll]
  | cons r rest ih =>
    simp [interpretAll, List.map, void_right, ih]

/-- **Theorem 20.3 (Universal Depth Bound on Interpretive Richness).**
    Interpretive richness ≤ total background depth + |receivers| × depth(signal).

    *Ricoeur*: The "surplus of meaning" is bounded — even the richest text
    can only generate bounded total interpretation, proportional to the
    community's existing hermeneutic capacity plus the text's complexity. -/
theorem universal_depth_bound (reps : List I) (s : I) :
    interpretiveRichness reps s ≤ depthSum reps + reps.length * IdeaticSpace.depth s := by
  induction reps with
  | nil => simp [interpretiveRichness, depthSum, List.map]
  | cons r rest ih =>
    simp only [interpretiveRichness, List.map] at *
    rw [depthSum_cons, depthSum_cons]
    have hcomp := depth_compose_le r s
    have hlen : (r :: rest).length = rest.length + 1 := rfl
    rw [hlen]
    have hmul : (rest.length + 1) * IdeaticSpace.depth s =
                rest.length * IdeaticSpace.depth s + IdeaticSpace.depth s := by ring
    rw [hmul]
    linarith

/-- **Theorem 20.4 (Resonance Preservation — Resonant Backgrounds).**
    If two receivers resonate, their interpretations of any signal resonate.

    *Durkheim*: Agents sharing "collective consciousness" (resonance) will
    produce consonant interpretations of any cultural artifact. -/
theorem resonance_preservation {r₁ r₂ : I}
    (hr : IdeaticSpace.resonates r₁ r₂) (s : I) :
    IdeaticSpace.resonates
      (IdeaticSpace.compose r₁ s) (IdeaticSpace.compose r₂ s) := by
  exact resonance_compose_right hr s

/-- **Theorem 20.5 (Resonance Preservation — Resonant Signals).**
    The same receiver interpreting resonant signals produces resonant outcomes.

    *Literary theory*: A reader encountering similar texts (resonant signals)
    produces similar interpretations. -/
theorem resonance_signal_preservation (r : I) {s₁ s₂ : I}
    (hs : IdeaticSpace.resonates s₁ s₂) :
    IdeaticSpace.resonates
      (IdeaticSpace.compose r s₁) (IdeaticSpace.compose r s₂) := by
  exact resonance_compose_left r hs

/-- **Theorem 20.6 (Composition Closure).**
    Interpretations of interpretations are still compositions.
    If receiver `r₁` interprets signal `s`, producing `compose r₁ s`,
    and then receiver `r₂` interprets THAT, the result is `compose r₂ (compose r₁ s)`.

    *Geertz's thick description*: Interpretation layered upon interpretation
    is still interpretation — there is no escape from the hermeneutic circle,
    only deeper embedding within it. -/
theorem composition_closure (r₁ r₂ s : I) :
    IdeaticSpace.compose r₂ (IdeaticSpace.compose r₁ s) =
    IdeaticSpace.compose (IdeaticSpace.compose r₂ r₁) s := by
  rw [compose_assoc]

/-- **Theorem 20.7 (Empty Game Equilibrium).**
    A meaning game with no receivers is trivially in equilibrium.

    *Logic*: Universal quantification over an empty set is vacuously true. -/
theorem empty_game_equilibrium (s : I) :
    MeaningEquilibrium ⟨s, []⟩ := by
  intro x hx
  simp [MeaningGame.outcome, interpretAll, List.map] at hx

/-- **Theorem 20.8 (Singleton Game Equilibrium).**
    A meaning game with one receiver is always in equilibrium.

    *Solipsism*: A single interpreter always agrees with themselves. -/
theorem singleton_equilibrium (r s : I) :
    MeaningEquilibrium ⟨s, [r]⟩ := by
  intro x hx y hy
  simp [MeaningGame.outcome, interpretAll, List.map, List.mem_singleton] at hx hy
  rw [hx, hy]
  exact resonance_refl _

/-- **Theorem 20.9 (Depth as Resource — Void Has Zero Richness).**
    A group interpreting void has richness = total background depth.
    Void contributes zero marginal depth.

    *Economics of meaning*: The "cost" of interpretation comes entirely from
    the interpreters' backgrounds when the signal carries no content. -/
theorem void_signal_richness (reps : List I) :
    interpretiveRichness reps IdeaticSpace.void = depthSum reps := by
  induction reps with
  | nil => simp [interpretiveRichness, depthSum, List.map]
  | cons r rest ih =>
    simp only [interpretiveRichness, List.map] at *
    rw [depthSum_cons, depthSum_cons, void_right]
    linarith

/-- **Theorem 20.10 (Trivial Equilibrium — Empty Game).**
    A meaning game with no receivers always has void as an equilibrium.

    *Game theory*: The "babbling equilibrium" trivially exists when there
    is no audience — saying nothing to no one creates no disagreement. -/
theorem trivial_equilibrium_exists :
    MeaningEquilibrium (⟨IdeaticSpace.void, []⟩ : MeaningGame I) := by
  intro x hx
  simp [MeaningGame.outcome, interpretAll] at hx

/-- **Theorem 20.11 (Interpretation Self-Resonance).**
    Every individual interpretation resonates with itself.

    *Phenomenology*: Every act of understanding is internally coherent. -/
theorem interpretation_self_resonance (r s : I) :
    IdeaticSpace.resonates (IdeaticSpace.compose r s) (IdeaticSpace.compose r s) :=
  resonance_refl _

/-- **Theorem 20.12 (Double Interpretation Depth Bound).**
    Re-interpreting an interpretation has bounded depth.

    *Hermeneutic circle*: Each pass through the circle adds bounded complexity.
    Understanding deepens, but not without limit per step. -/
theorem double_interp_depth (r₁ r₂ s : I) :
    IdeaticSpace.depth (IdeaticSpace.compose r₂ (IdeaticSpace.compose r₁ s)) ≤
    IdeaticSpace.depth r₁ + IdeaticSpace.depth r₂ + IdeaticSpace.depth s := by
  have h1 := depth_compose_le r₂ (IdeaticSpace.compose r₁ s)
  have h2 := depth_compose_le r₁ s
  linarith

/-- **Theorem 20.13 (Resonant Community Equilibrium).**
    If all receivers pairwise resonate, the meaning game is in equilibrium
    for ANY signal.

    *Durkheim*: A community with strong "collective consciousness" (universal
    pairwise resonance) achieves interpretive consensus regardless of the
    stimulus. Shared culture makes shared understanding automatic. -/
theorem resonant_community_equilibrium (receivers : List I) (s : I)
    (hres : ∀ r₁ ∈ receivers, ∀ r₂ ∈ receivers, IdeaticSpace.resonates r₁ r₂) :
    MeaningEquilibrium ⟨s, receivers⟩ := by
  intro x hx y hy
  simp [MeaningGame.outcome, interpretAll, List.map] at hx hy
  obtain ⟨r₁, hr₁_mem, hr₁_eq⟩ := hx
  obtain ⟨r₂, hr₂_mem, hr₂_eq⟩ := hy
  rw [← hr₁_eq, ← hr₂_eq]
  exact resonance_compose_right (hres r₁ hr₁_mem r₂ hr₂_mem) s

/-- **Theorem 20.14 (Void Receiver Transparency).**
    A receiver with void background returns the signal unchanged.

    *Tabula rasa*: An empty mind is a perfect mirror for the signal. -/
theorem void_receiver_transparent (s : I) :
    IdeaticSpace.compose IdeaticSpace.void s = s := by
  simp

/-- **Theorem 20.15 (Interpretation Depth Non-Negativity).**
    Interpretive richness is always ≥ 0.

    *Methodology*: Interpretation always produces non-negative hermeneutic content.
    (This is trivial for ℕ but establishes a conceptual baseline.) -/
theorem richness_nonneg (reps : List I) (s : I) :
    0 ≤ interpretiveRichness reps s := Nat.zero_le _

/-- **Theorem 20.16 (Empty Repertoire Zero Richness).**
    No receivers means zero interpretive richness.

    *Information theory*: A message with no audience generates no meaning. -/
theorem empty_richness (s : I) :
    interpretiveRichness [] s = 0 := by
  simp [interpretiveRichness, depthSum, List.map]

/-- **Theorem 20.17 (Singleton Richness Bound).**
    A single receiver's interpretive richness ≤ depth(r) + depth(s).

    *Individual hermeneutics*: One person's interpretive effort is bounded
    by their background plus the signal's complexity. -/
theorem singleton_richness_bound (r s : I) :
    interpretiveRichness [r] s ≤ IdeaticSpace.depth r + IdeaticSpace.depth s := by
  simp [interpretiveRichness, List.map, depthSum_cons, depthSum]
  exact depth_compose_le r s

/-- **Theorem 20.18 (Game Outcome Length).**
    The number of interpretations equals the number of receivers.

    *Social theory*: Every voice in the community produces exactly one interpretation. -/
theorem outcome_length (g : MeaningGame I) :
    g.outcome.length = g.receivers.length := by
  simp [MeaningGame.outcome, interpretAll]

/-- **Theorem 20.19 (Associativity of Iterated Interpretation).**
    Three layers of interpretation can be re-bracketed.
    `compose r₃ (compose r₂ (compose r₁ s)) = compose (compose r₃ r₂) (compose r₁ s)`.

    *Gadamer*: The hermeneutic circle has no privileged entry point —
    re-bracketing the layers of interpretation doesn't change the result. -/
theorem iterated_interpretation_assoc (r₁ r₂ r₃ s : I) :
    IdeaticSpace.compose r₃ (IdeaticSpace.compose r₂ (IdeaticSpace.compose r₁ s)) =
    IdeaticSpace.compose (IdeaticSpace.compose r₃ r₂) (IdeaticSpace.compose r₁ s) := by
  rw [compose_assoc]

/-- **Theorem 20.20 (The Meaning Game Grand Synthesis).**
    For any meaning game with resonant receivers: the total interpretive richness
    is bounded, and the game is in equilibrium. Both fundamental properties hold
    simultaneously.

    *Geertz's "Interpretation of Cultures"*: A culturally coherent community
    (resonant receivers) always achieves both:
    (1) bounded total interpretive effort, and
    (2) mutual comprehensibility of all interpretations.

    This is the grand unification: resource bounds and hermeneutic consensus
    are simultaneously achievable whenever the interpretive community shares
    cultural resonance. -/
theorem grand_synthesis (receivers : List I) (s : I)
    (hres : ∀ r₁ ∈ receivers, ∀ r₂ ∈ receivers, IdeaticSpace.resonates r₁ r₂) :
    interpretiveRichness receivers s ≤ depthSum receivers + receivers.length * IdeaticSpace.depth s ∧
    MeaningEquilibrium ⟨s, receivers⟩ :=
  ⟨universal_depth_bound receivers s, resonant_community_equilibrium receivers s hres⟩

end IDT.Signal.Ch20
