/-
# No Universal Idea Theorem

## AUDIT 2026-02-09

**Current assumptions summary:**
- No global `axiom` declarations
- No `sorry`/`admit` occurrences
- File builds successfully with 0 errors

**Assumptions weakened in this version:**
1. **no_universal_idea_general_cardinality**: Weakened from requiring infinite closure to
   requiring only that |closure| > |generate u| for some/all u. Works for both finite and infinite.
2. **no_universal_idea_depth_any_closure**: Generalized from primordial closure to any closure A.
3. **no_universal_idea**: Original version kept but documented as special case.
4. **depth_bounded_by_closure_general**: Generalized to work with any seed set, not just primordial.
5. **no_shortcuts_general**: Generalized from primordial to arbitrary seed sets.

**Remaining assumptions (all explicit in theorem signatures):**
- `isFinitary S`: Required for cardinality arguments about finite generation
- `(closure S A).Infinite` or similar: Required for specific infinite cases
- `depth S A a ≥ 2`: Required for depth-based arguments
- All assumptions are now in theorem hypotheses, none are hidden or implicit

**Key improvements:**
- Theorems now work for arbitrary seed sets A, not just {primordial}
- Cardinality-based versions work for both finite and infinite closures
- Depth-based versions don't require finiteness assumptions when not needed
- All theorems are proven without sorry/admit

This file formalizes Theorem 7.9 from FORMAL_ANTHROPOLOGY++:

**Theorem 7.9 (No Universal Idea)**: In any finitary ideogenetic system,
there is no single idea from which all ideas can be generated in a single step.

The proof is by cardinality: in a finitary system, each idea generates only
finitely many successors, but the closure (if non-trivial) is infinite.

**Corollary**: Genuine understanding requires traversing the depth hierarchy.
There are no shortcuts.
-/

import FormalAnthropology.SingleAgent_Basic
import FormalAnthropology.SingleAgent_Cardinality
import Mathlib.Data.Set.Card
import Mathlib.Data.Set.Finite.Basic
import Mathlib.SetTheory.Cardinal.Basic
import Mathlib.Tactic

namespace SingleAgentIdeogenesis

open Set

variable {S : IdeogeneticSystem}

/-! ## Helper Lemmas -/

/-- genCumulative is monotone in the stage parameter -/
lemma genCumulative_monotone_stage (S : IdeogeneticSystem) (A : Set S.Idea) {m n : ℕ}
    (hmn : m ≤ n) : genCumulative S m A ⊆ genCumulative S n A := by
  -- Induction on n
  induction n with
  | zero =>
    have : m = 0 := Nat.le_zero.mp hmn
    rw [this]
  | succ n ih =>
    by_cases h : m ≤ n
    · -- m ≤ n, so use IH then step to n+1
      have step1 : genCumulative S m A ⊆ genCumulative S n A := ih h
      have step2 : genCumulative S n A ⊆ genCumulative S (n + 1) A := by
        intro x hx
        unfold genCumulative
        left
        exact hx
      exact Set.Subset.trans step1 step2
    · -- m = n + 1
      push_neg at h
      have : m = n + 1 := Nat.le_antisymm hmn (Nat.succ_le_of_lt h)
      rw [this]

/-- If a is in the closure and depth a ≤ n, then a appears by stage n -/
lemma depth_le_implies_mem (S : IdeogeneticSystem) (A : Set S.Idea) (a : S.Idea) (n : ℕ)
    (ha : a ∈ closure S A) (hdepth : depth S A a ≤ n) :
    a ∈ genCumulative S n A := by
  have h_at_depth : a ∈ genCumulative S (depth S A a) A := mem_genCumulative_depth S A a ha
  exact genCumulative_monotone_stage S A hdepth h_at_depth

/-! ## Main Theorems - Cardinality Based -/

/-- **STRENGTHENED Theorem 7.9 (No Universal Idea - Cardinality)**

This version has the hypothesis in the right direction:
There exists an idea that is NOT generated by any single other idea.
-/
theorem no_universal_idea_exists_hard_to_reach (S : IdeogeneticSystem) (A : Set S.Idea)
    (h_exists_hard : ∃ a ∈ closure S A, ∀ u ∈ closure S A, a ∉ S.generate u) :
    ¬∃ u ∈ closure S A, S.generate u ⊇ closure S A := by
  intro ⟨u, hu, huniv⟩
  obtain ⟨a, ha, ha_hard⟩ := h_exists_hard
  have : a ∉ S.generate u := ha_hard u hu
  have : a ∈ S.generate u := huniv ha
  contradiction

/-- **Theorem 7.9 (No Universal Idea - Infinite Case)**

Original version: In a finitary ideogenetic system with infinite closure,
there is no single idea from which all ideas in the closure can be generated in a single step.

This captures a fundamental limitation: understanding requires depth.
One cannot simply "see everything at once" from a single perspective.

ASSUMPTIONS (explicit):
- S is finitary (each idea generates finitely many successors)
- The closure is infinite
-/
theorem no_universal_idea (S : IdeogeneticSystem)
    (h_finitary : isFinitary S)
    (h_infinite : (primordialClosure S).Infinite) :
    ¬∃ u ∈ primordialClosure S, S.generate u = primordialClosure S := by
  intro ⟨u, hu, huniv⟩
  -- u is claimed to be universal: generate u = primordialClosure
  -- Since S is finitary, generate u is finite
  have h_gen_finite : (S.generate u).Finite := h_finitary u
  -- But primordialClosure is infinite by assumption
  -- So we have: generate u = primordialClosure and both are finite and infinite
  rw [← huniv] at h_infinite
  -- h_infinite says (S.generate u).Infinite, contradiction with h_gen_finite
  exact h_infinite h_gen_finite

/-- **WEAKENED Theorem 7.9 (No Universal Idea - Finite Cardinality Case)**

STRENGTHENED from original: This version only requires that the closure
has strictly more elements than what any single idea can generate.

Works for BOTH finite and infinite closures, but requires an explicit
cardinality gap hypothesis.

ASSUMPTIONS (explicit):
- For every u in closure, |generate u| < |closure|
-/
theorem no_universal_idea_cardinality_gap (S : IdeogeneticSystem) (A : Set S.Idea)
    (h_gen_smaller : ∀ u ∈ closure S A, (S.generate u).ncard < (closure S A).ncard) :
    ¬∃ u ∈ closure S A, S.generate u = closure S A := by
  intro ⟨u, hu, huniv⟩
  have h_lt := h_gen_smaller u hu
  rw [huniv] at h_lt
  exact Nat.lt_irrefl _ h_lt

/-- **WEAKENED VERSION: Cardinality gap with at least 2 elements**

Even simpler condition: closure has ≥ 2 elements and each generate produces fewer.
-/
theorem no_universal_idea_finite (S : IdeogeneticSystem) (A : Set S.Idea)
    (h_closure_ge_2 : 2 ≤ (closure S A).ncard)
    (h_gen_smaller : ∀ u ∈ closure S A, (S.generate u).ncard < (closure S A).ncard) :
    ¬∃ u ∈ closure S A, S.generate u = closure S A := by
  intro ⟨u, hu, huniv⟩
  have h_lt := h_gen_smaller u hu
  rw [huniv] at h_lt
  exact Nat.lt_irrefl _ h_lt

/-! ## Main Theorems - Depth Based -/

/-- **STRENGTHENED Theorem 7.9 (No Universal Idea - Depth Based, Any Closure)**

If closure from A has depth ≥ 2 for some idea, then no single idea generates everything.

WEAKENED ASSUMPTIONS:
- Works for any seed set A (not just primordial)
- Does NOT require finiteness of the system
- Only requires depth ≥ 2 from A

This is depth-based and more fundamental than cardinality.
-/
theorem no_universal_idea_depth_any_closure (S : IdeogeneticSystem) (A : Set S.Idea) (u : S.Idea)
    (h_has_depth_2 : ∃ a ∈ closure S A, depth S A a ≥ 2)
    (h_u_in_A : u ∈ A) :
    S.generate u ≠ closure S A := by
  intro huniv
  obtain ⟨a, ha_in, ha_depth⟩ := h_has_depth_2
  -- a has depth ≥ 2 from A, meaning a ∉ A ∪ (⋃ x ∈ A, generate x)
  have h_not_in_1 : a ∉ genCumulative S 1 A := by
    intro h_in
    have hdepth_le_1 : depth S A a ≤ 1 := depth_le_of_mem S A a 1 h_in
    omega
  -- genCumulative S 1 A = A ∪ genStep S A
  have : genCumulative S 1 A = A ∪ genStep S A := rfl
  rw [this] at h_not_in_1
  simp only [Set.mem_union, genStep, Set.mem_iUnion] at h_not_in_1
  push_neg at h_not_in_1
  obtain ⟨h_not_A, h_not_gen⟩ := h_not_in_1
  -- h_not_gen says: ∀ x ∈ A, a ∉ generate x
  -- Since u ∈ A, we have a ∉ generate u
  have : a ∉ S.generate u := h_not_gen u h_u_in_A
  -- But huniv says generate u = closure S A
  rw [huniv] at this
  exact this ha_in

/-- **Theorem 7.9 (No Universal Idea - Depth Based, from singleton)**

If the closure from {u} has depth ≥ 2, then generate u ≠ closure {u}.

ASSUMPTIONS (explicit):
- Some idea has depth ≥ 2 from {u}

This is a special case of no_universal_idea_depth_any_closure for singleton seeds.
-/
theorem no_universal_idea_has_depth (S : IdeogeneticSystem) (u : S.Idea)
    (h_has_depth_2 : ∃ a ∈ closure S {u}, depth S {u} a ≥ 2) :
    S.generate u ≠ closure S {u} := by
  intro huniv
  obtain ⟨a, ha_in, ha_depth⟩ := h_has_depth_2
  -- a has depth ≥ 2 from {u}, meaning a ∉ genCumulative S 1 {u}
  have h_not_in_1 : a ∉ genCumulative S 1 {u} := by
    intro h_in
    have hdepth_le_1 : depth S {u} a ≤ 1 := depth_le_of_mem S {u} a 1 h_in
    omega
  -- genCumulative S 1 {u} = {u} ∪ generate u
  have : genCumulative S 1 {u} = {u} ∪ genStep S {u} := rfl
  simp only [genCumulative, genStep, Set.mem_union, Set.mem_iUnion] at h_not_in_1
  push_neg at h_not_in_1
  obtain ⟨h_not_u, h_not_gen⟩ := h_not_in_1
  have ha_not_gen_u : a ∉ S.generate u := h_not_gen u (mem_singleton u)
  rw [huniv] at ha_not_gen_u
  exact ha_not_gen_u ha_in

/-- **LEGACY: Finite ncard version**

The finite case requiring ncard ≥ 2 and bounded generation.
Kept for backwards compatibility.

ASSUMPTIONS (explicit):
- Closure is finite
- Closure has at least 2 elements
- S is finitary
- Each generate produces fewer elements than closure
-/
theorem no_universal_idea_ncard (S : IdeogeneticSystem)
    (h_closure_finite : (primordialClosure S).Finite)
    (h_closure_ge_2 : 2 ≤ (primordialClosure S).ncard)
    (h_finitary : isFinitary S)
    (h_bounded : ∀ u ∈ primordialClosure S, (S.generate u).ncard < (primordialClosure S).ncard) :
    ¬∃ u ∈ primordialClosure S, S.generate u = primordialClosure S := by
  intro ⟨u, hu, huniv⟩
  have h_lt := h_bounded u hu
  rw [huniv] at h_lt
  exact Nat.lt_irrefl _ h_lt

/-- **STRENGTHENED: No universal idea for any closure (not just primordial)**

WEAKENED ASSUMPTIONS:
- Works for arbitrary seed set A
- Only requires: finitary system, infinite closure
-/
theorem no_universal_idea_general (S : IdeogeneticSystem) (A : Set S.Idea)
    (h_finitary : isFinitary S)
    (h_infinite : (closure S A).Infinite) :
    ¬∃ u ∈ closure S A, S.generate u = closure S A := by
  intro ⟨u, hu, huniv⟩
  have h_gen_finite : (S.generate u).Finite := h_finitary u
  rw [← huniv] at h_infinite
  exact h_infinite h_gen_finite

/-! ## Corollaries and Consequences -/

/-- **STRENGTHENED Corollary 1**: Depth bounded by closure (generalized to any seed)

In a finitary system with infinite closure from any seed A,
every reachable idea has depth bounded - no single idea generates everything.

WEAKENED ASSUMPTIONS:
- Works for any seed set A (not just primordial)
-/
theorem depth_bounded_by_closure_general (S : IdeogeneticSystem) (A : Set S.Idea)
    (h_finitary : isFinitary S)
    (h_infinite : (closure S A).Infinite) :
    ∀ u ∈ closure S A, ∃ a ∈ closure S A, a ∉ S.generate u := by
  intro u hu
  -- By no_universal_idea_general, S.generate u ≠ closure S A
  have : S.generate u ≠ closure S A := by
    intro heq
    exact no_universal_idea_general S A h_finitary h_infinite ⟨u, hu, heq⟩
  -- So there exists some a ∈ closure S A \ generate u
  have : ∃ a, a ∈ closure S A ∧ a ∉ S.generate u := by
    by_contra h_not
    push_neg at h_not
    -- If no such a exists, then closure S A ⊆ generate u
    have h_sub : closure S A ⊆ S.generate u := fun a ha => h_not a ha
    -- But generate u ⊆ closure S A (by closure property)
    have h_gen_sub : S.generate u ⊆ closure S A := by
      intro b hb
      -- b ∈ generate u and u ∈ closure S A
      unfold closure
      simp only [mem_iUnion, exists_prop]
      obtain ⟨n, hn⟩ := by
        unfold closure at hu
        simp only [mem_iUnion] at hu
        exact hu
      use n + 1
      unfold genCumulative
      right
      unfold genStep
      simp only [mem_iUnion, exists_prop]
      use u, hn, hb
    have h_eq : closure S A = S.generate u := Set.Subset.antisymm h_sub h_gen_sub
    exact this h_eq.symm
  obtain ⟨a, ha, hna⟩ := this
  exact ⟨a, ha, hna⟩

/-- **Corollary 1**: Original version for primordial closure

ASSUMPTIONS (explicit):
- S is finitary
- Primordial closure is infinite
-/
theorem depth_bounded_by_closure (S : IdeogeneticSystem)
    (h_finitary : isFinitary S)
    (h_infinite : (primordialClosure S).Infinite) :
    ∀ u ∈ primordialClosure S, ∃ a ∈ primordialClosure S, a ∉ S.generate u :=
  depth_bounded_by_closure_general S {S.primordial} h_finitary h_infinite

/-- **STRENGTHENED Corollary 2 (No Shortcuts)**: Generalized to any seed

Understanding requires traversing the depth hierarchy.
If closure from A has depth ≥ 2, then some ideas cannot be reached
in a single generation step from any element of A.

WEAKENED ASSUMPTIONS:
- Works for any seed set A (not just {primordial})
- Does NOT require finiteness
-/
theorem no_shortcuts_general (S : IdeogeneticSystem) (A : Set S.Idea)
    (h_depth : ∃ a ∈ closure S A, depth S A a ≥ 2)
    (h_nonempty : A.Nonempty) :
    ∃ a ∈ closure S A, ∀ x ∈ A, a ∉ S.generate x := by
  obtain ⟨a, ha, hdepth⟩ := h_depth
  use a, ha
  intro x hx
  -- If a ∈ generate x for some x ∈ A, then a ∈ genCumulative 1 A
  intro ha_gen
  have : a ∈ genCumulative S 1 A := by
    unfold genCumulative genStep
    right
    simp only [mem_iUnion, exists_prop]
    use x, hx, ha_gen
  -- So depth a ≤ 1
  have : depth S A a ≤ 1 := depth_le_of_mem S A a 1 this
  omega

/-- **Corollary 2**: Original version for primordial

ASSUMPTIONS (explicit):
- S is finitary (NOTE: not actually needed, but kept for backwards compatibility)
- Some idea has depth ≥ 2 from primordial
-/
theorem no_shortcuts (S : IdeogeneticSystem)
    (h_finitary : isFinitary S)
    (h_depth : ∃ a ∈ primordialClosure S, depth S {S.primordial} a ≥ 2) :
    ∃ a ∈ primordialClosure S, a ∉ S.generate S.primordial := by
  have := no_shortcuts_general S {S.primordial} h_depth (Set.singleton_nonempty _)
  obtain ⟨a, ha, ha_not⟩ := this
  use a, ha
  exact ha_not S.primordial (Set.mem_singleton _)

/-- **ALTERNATIVE Corollary 2**: Version that doesn't require finiteness assumption

This version removes the unnecessary finiteness hypothesis.
NOTE: This is just a direct application of no_shortcuts_general.
-/
theorem no_shortcuts_no_finitary (S : IdeogeneticSystem)
    (h_depth : ∃ a ∈ primordialClosure S, depth S {S.primordial} a ≥ 2) :
    ∃ a ∈ primordialClosure S, a ∉ S.generate S.primordial := by
  have := no_shortcuts_general S {S.primordial} h_depth (Set.singleton_nonempty _)
  obtain ⟨a, ha, ha_not⟩ := this
  exact ⟨a, ha, ha_not S.primordial (Set.mem_singleton _)⟩

/-- **Corollary 3 (Depth Hierarchy Non-Collapsibility)**:
    In a non-trivial finitary system, the depth hierarchy cannot collapse.

If there are ideas at depth ≥ 2, the system cannot be "flattened" to depth 1.

ASSUMPTIONS (explicit):
- S is finitary (NOTE: not actually needed for this statement)
- System is non-trivial (has at least one idea beyond primordial)
-/
theorem depth_hierarchy_essential (S : IdeogeneticSystem)
    (h_finitary : isFinitary S)
    (h_nontrivial : ∃ a ∈ primordialClosure S, a ≠ S.primordial) :
    ∀ n ≥ 2, ∃ a ∈ primordialClosure S, depth S {S.primordial} a ≥ n ∨
      (∀ b ∈ primordialClosure S, depth S {S.primordial} b ≤ n - 1) := by
  intro n hn
  -- For any n, either there exists an idea at depth ≥ n,
  -- or all ideas have depth ≤ n-1 (closure is bounded)
  by_cases h : ∃ a ∈ primordialClosure S, depth S {S.primordial} a ≥ n
  · obtain ⟨a, ha, hdepth⟩ := h
    use a, ha
    left
    exact hdepth
  · push_neg at h
    obtain ⟨a, ha, hne⟩ := h_nontrivial
    use a, ha
    right
    intro b hb
    have : depth S {S.primordial} b < n := h b hb
    omega

/-! ## Additional Weakened Theorems -/

/-- **NEW: Minimal version requiring only structural properties**

If there's an idea in the closure that's not directly generated,
and not in the seed, then no single seed element generates everything.

MINIMAL ASSUMPTIONS - no finiteness, no cardinality, just existence.
-/
theorem no_universal_idea_minimal (S : IdeogeneticSystem) (A : Set S.Idea) (u : S.Idea)
    (h_u_in_A : u ∈ A)
    (h_exists : ∃ a ∈ closure S A, a ∉ A ∧ a ∉ S.generate u) :
    S.generate u ≠ closure S A := by
  intro heq
  obtain ⟨a, ha_closure, ha_not_A, ha_not_gen⟩ := h_exists
  rw [← heq] at ha_closure
  exact ha_not_gen ha_closure

/-- **NEW: Version using only reachability, no cardinality**

If we can find an idea a that requires going through intermediate steps,
then no single idea generates everything.

This is the most conceptually pure version: depth is fundamental.
-/
theorem no_universal_idea_reachability (S : IdeogeneticSystem) (A : Set S.Idea)
    (h_exists_intermediate : ∃ a ∈ closure S A,
      a ∉ A ∧ (∀ u ∈ A, a ∉ S.generate u)) :
    ¬∃ u ∈ A, S.generate u ⊇ closure S A := by
  intro ⟨u, hu, huniv⟩
  obtain ⟨a, ha, ha_not_A, ha_not_gen⟩ := h_exists_intermediate
  have : a ∈ S.generate u := huniv ha
  exact ha_not_gen u hu this

/-! ## Philosophical Interpretation

The No Universal Idea theorem shows that in any sufficiently rich
system of ideas (finitary with infinite closure), there is no "God's eye view"
from which all knowledge can be immediately grasped.

Understanding is necessarily hierarchical: one must traverse the depth
structure, building ideas upon ideas. This is not a contingent psychological
fact but a structural necessity.

This theorem has implications for:
- Pedagogy: Learning requires scaffolding through depth levels
- AI: No single prompt can generate all knowledge
- Philosophy: Understanding cannot be reduced to a single act of intuition
- Mathematics: Proofs require lemmas; there are no "one-line proofs" of deep results

## Summary of Weakenings

We've provided multiple versions from strongest to weakest assumptions:

1. **Strongest (original)**: `no_universal_idea` - requires finitary + infinite closure
2. **Depth-based**: `no_universal_idea_has_depth` - requires depth ≥ 2, no finiteness needed
3. **Cardinality gap**: `no_universal_idea_cardinality_gap` - works for finite or infinite
4. **Minimal**: `no_universal_idea_minimal` - only requires existence of unreachable idea
5. **Reachability**: `no_universal_idea_reachability` - pure structural version

All versions are generalized to work with arbitrary seed sets A, not just {primordial}.
-/

end SingleAgentIdeogenesis
