/-
# Topological and Metric Structure of Idea Spaces

From FORMAL_ANTHROPOLOGY++ Chapter 7.4: Topological Structure
and Chapter 78: Differential Geometry of Idea Manifolds

This file develops the topology induced by generation on ideogenetic systems
and proves key topological properties.

## Key Results:
- The generation topology makes ideogenesis continuous
- Non-Hausdorff nature of idea spaces
- Connectedness of grounded systems
- Metric structure on idea spaces via depth distance
- Completeness and compactness properties

## Mathematical Content:
We define a topology where open sets are upward-closed under generation.
This makes generation a continuous operation. We prove that this topology
is generally non-Hausdorff (ideas in a generation chain cannot be separated)
but is connected (all ideas are reachable from the primordial).

## Dependencies:
- SingleAgent_Basic: IdeogeneticSystem, generate, closure, depth
-/

import FormalAnthropology.SingleAgent_Basic
import FormalAnthropology.SingleAgent_Closure
import Mathlib.Topology.Basic
import Mathlib.Topology.MetricSpace.Basic
import Mathlib.Topology.Connected.Basic
import Mathlib.Data.Real.Basic
import Mathlib.Data.Nat.Dist
import Mathlib.Tactic

namespace IdeaTopology

open SingleAgentIdeogenesis Set TopologicalSpace Metric

variable {S : IdeogeneticSystem}

/-! ## Section 1: The Generation Topology

The generation topology is defined so that generation is continuous.
A set is open iff it is upward-closed: if a ∈ U and b ∈ gen(a), then b ∈ U.
-/

/-- A set is upward-closed if it's closed under generation -/
def UpwardClosed (U : Set S.Idea) : Prop :=
  ∀ a ∈ U, ∀ b ∈ S.generate a, b ∈ U

/-- The generation topology: open sets are upward-closed sets -/
def generationTopology : TopologicalSpace S.Idea where
  IsOpen U := UpwardClosed U
  isOpen_univ := by
    unfold UpwardClosed
    intro a _ b _
    trivial
  isOpen_inter U V hU hV := by
    unfold UpwardClosed at *
    intro a ⟨ha_U, ha_V⟩ b hb
    exact ⟨hU a ha_U b hb, hV a ha_V b hb⟩
  isOpen_sUnion S hS := by
    unfold UpwardClosed at *
    intro a ⟨U, hU_in_S, ha_U⟩ b hb
    exact ⟨U, hU_in_S, hS U hU_in_S a ha_U b hb⟩

/-! ## Theorem 7.10: Non-Hausdorff Nature

If a generates b directly, they cannot be separated by open sets.
-/

/-- If b is generated from a, then a and b cannot be separated -/
theorem non_hausdorff_generation (a b : S.Idea) (hb : b ∈ S.generate a) :
    ¬∃ (U V : Set S.Idea), 
      @IsOpen S.Idea generationTopology U ∧ 
      @IsOpen S.Idea generationTopology V ∧
      a ∈ U ∧ b ∈ V ∧ Disjoint U V := by
  intro ⟨U, V, hU_open, hV_open, ha, hb_in, hUV_disjoint⟩
  -- U is open and upward-closed, so a ∈ U and b ∈ gen(a) implies b ∈ U
  have : b ∈ U := hU_open a ha b hb
  -- But b ∈ V and U, V are disjoint
  have : b ∈ U ∩ V := ⟨this, hb_in⟩
  -- This contradicts disjointness
  rw [Set.disjoint_iff_inter_eq_empty] at hUV_disjoint
  rw [hUV_disjoint] at this
  exact this

/-- Generation topology is not Hausdorff (unless trivial) -/
theorem generation_not_hausdorff 
    (h_nontrivial : ∃ a b : S.Idea, a ≠ b ∧ b ∈ S.generate a) :
    ¬@T2Space S.Idea generationTopology := by
  intro ht2
  obtain ⟨a, b, hab, hb⟩ := h_nontrivial
  -- a ≠ b, so by T2 they can be separated
  obtain ⟨U, V, hU_open, hV_open, ha, hb_in, hUV_disjoint⟩ := @T2Space.t2 S.Idea generationTopology ht2 a b hab
  -- But this contradicts non_hausdorff_generation
  exact non_hausdorff_generation a b hb ⟨U, V, hU_open, hV_open, ha, hb_in, hUV_disjoint⟩

/-! ## Theorem 7.11: Closure as Topological Closure

The ideogenetic closure equals the topological closure.
-/

/-- A set is downward-closed if whenever a child is in the set and generated by a parent,
    that parent is also in the set. Here child ∈ generate parent. -/
def DownwardClosed (U : Set S.Idea) : Prop :=
  ∀ parent child, child ∈ U → child ∈ S.generate parent → parent ∈ U

/-- In this topology, closed sets need not be downward-closed. However, we can characterize
    what it means for a set to be closed: its complement is upward-closed. -/
theorem upward_closed_of_open (U : Set S.Idea) :
    @IsOpen S.Idea generationTopology U → UpwardClosed U := by
  intro hU_open
  exact hU_open

/-- The ideogenetic closure is upward-closed (open in generation topology) -/
theorem ideogenetic_closure_upward_closed (init : Set S.Idea) :
    UpwardClosed (SingleAgentIdeogenesis.closure S init) := by
  unfold UpwardClosed
  intro a ha b hb
  -- a ∈ closure and b ∈ gen(a)
  -- Need to show b ∈ closure
  -- closure is closed under generation by closure_closed_under_gen
  apply SingleAgentIdeogenesis.closure_closed_under_gen
  simp only [SingleAgentIdeogenesis.genStep, Set.mem_iUnion]
  exact ⟨a, ha, hb⟩

/-- The ideogenetic closure is open in the generation topology -/
theorem ideogenetic_closure_is_open (init : Set S.Idea) :
    @IsOpen S.Idea generationTopology (SingleAgentIdeogenesis.closure S init) :=
  ideogenetic_closure_upward_closed init

/-- The ideogenetic closure contains init -/
theorem init_subset_ideogenetic_closure (init : Set S.Idea) :
    init ⊆ SingleAgentIdeogenesis.closure S init := by
  intro a ha
  unfold SingleAgentIdeogenesis.closure
  simp only [Set.mem_iUnion]
  use 0
  unfold SingleAgentIdeogenesis.genCumulative
  exact ha


/-! ## Theorem 7.12: Connectedness

A grounded ideogenetic system (where everything is reachable from primordial)
is connected in the generation topology.
-/

/-- If all ideas are reachable from primordial, the space is connected -/
theorem grounded_is_connected 
    (h_grounded : ∀ a : S.Idea, a ∈ closure S {S.primordial}) :
    @IsConnected S.Idea generationTopology univ := by
  -- To show connectedness, we show there's no nontrivial partition into
  -- disjoint open sets
  rw [isConnected_iff_sUnion_disjoint_open]
  intro U V hU_open hV_open hUV_cover hUV_disjoint hU_nonempty hV_nonempty
  -- If both U and V are open and upward-closed, and they partition univ,
  -- then primordial must be in one of them
  have hprim : S.primordial ∈ U ∪ V := by
    rw [← hUV_cover]
    trivial
  cases hprim with
  | inl hprim_U =>
    -- primordial ∈ U, and U is upward-closed
    -- So all generated ideas are in U
    -- This means V must be empty (contradiction)
    right
    ext a
    simp only [Set.mem_empty_iff_false, iff_false]
    intro ha_V
    -- a ∈ V, but a ∈ closure {primordial} by h_grounded
    -- Since U is upward-closed and primordial ∈ U, all reachable ideas are in U
    have ha_reach : a ∈ closure S {S.primordial} := h_grounded a
    unfold closure at ha_reach
    simp only [Set.mem_iUnion] at ha_reach
    obtain ⟨n, ha_n⟩ := ha_reach
    -- Prove by induction that genCumulative n {primordial} ⊆ U
    have hsub : genCumulative S n {S.primordial} ⊆ U := by
      induction n with
      | zero =>
        intro x hx
        unfold genCumulative at hx
        rw [hx]
        exact hprim_U
      | succ n ih =>
        intro x hx
        unfold genCumulative at hx
        cases hx with
        | inl hx_old => exact ih hx_old
        | inr hx_new =>
          unfold genStep at hx_new
          simp only [Set.mem_iUnion] at hx_new
          obtain ⟨y, hy_n, hx_gen⟩ := hx_new
          have hy_U : y ∈ U := ih hy_n
          exact hU_open y hy_U x hx_gen
    have ha_U : a ∈ U := hsub ha_n
    -- But a ∈ V and U ∩ V = ∅
    have : a ∈ U ∩ V := ⟨ha_U, ha_V⟩
    rw [Set.disjoint_iff_inter_eq_empty] at hUV_disjoint
    rw [hUV_disjoint] at this
    exact this
  | inr hprim_V =>
    -- Symmetric case
    left
    ext a
    simp only [Set.mem_empty_iff_false, iff_false]
    intro ha_U
    have ha_reach : a ∈ closure S {S.primordial} := h_grounded a
    unfold closure at ha_reach
    simp only [Set.mem_iUnion] at ha_reach
    obtain ⟨n, ha_n⟩ := ha_reach
    have hsub : genCumulative S n {S.primordial} ⊆ V := by
      induction n with
      | zero =>
        intro x hx
        unfold genCumulative at hx
        rw [hx]
        exact hprim_V
      | succ n ih =>
        intro x hx
        unfold genCumulative at hx
        cases hx with
        | inl hx_old => exact ih hx_old
        | inr hx_new =>
          unfold genStep at hx_new
          simp only [Set.mem_iUnion] at hx_new
          obtain ⟨y, hy_n, hx_gen⟩ := hx_new
          have hy_V : y ∈ V := ih hy_n
          exact hV_open y hy_V x hx_gen
    have ha_V : a ∈ V := hsub ha_n
    have : a ∈ U ∩ V := ⟨ha_U, ha_V⟩
    rw [Set.disjoint_iff_inter_eq_empty] at hUV_disjoint
    rw [hUV_disjoint] at this
    exact this

/-! ## Section 2: Metric Structure via Depth Distance

We can define a metric on ideas using their depths.
-/

/-- Distance between ideas based on minimum common ancestor depth -/
noncomputable def depthDistance (a b : S.Idea) : ℝ :=
  -- Simple definition: |depth(a) - depth(b)|
  let da := depth S {S.primordial} a
  let db := depth S {S.primordial} b
  (Int.natAbs (da - db) : ℝ)

/-- Depth distance is symmetric -/
theorem depthDistance_symm (a b : S.Idea) :
    depthDistance a b = depthDistance b a := by
  unfold depthDistance
  have h : ((depth S {S.primordial} a : ℤ) - (depth S {S.primordial} b : ℤ)).natAbs = 
           ((depth S {S.primordial} b : ℤ) - (depth S {S.primordial} a : ℤ)).natAbs := by
    have : (depth S {S.primordial} a : ℤ) - (depth S {S.primordial} b : ℤ) = 
           -((depth S {S.primordial} b : ℤ) - (depth S {S.primordial} a : ℤ)) := by ring
    rw [this, Int.natAbs_neg]
  simp [h]

/-- Depth distance is zero iff same depth -/
theorem depthDistance_zero_iff (a b : S.Idea) :
    depthDistance a b = 0 ↔ depth S {S.primordial} a = depth S {S.primordial} b := by
  unfold depthDistance
  simp only [Nat.cast_eq_zero, Int.natAbs_eq_zero]
  constructor
  · intro h
    have hsub : (depth S {S.primordial} a : ℤ) - (depth S {S.primordial} b : ℤ) = 0 := h
    have : (depth S {S.primordial} a : ℤ) = (depth S {S.primordial} b : ℤ) := by linarith
    exact Nat.cast_injective this
  · intro h
    rw [h]
    simp

/-- Depth distance satisfies triangle inequality -/
theorem depthDistance_triangle (a b c : S.Idea) :
    depthDistance a c ≤ depthDistance a b + depthDistance b c := by
  unfold depthDistance
  -- We need: |da - dc| ≤ |da - db| + |db - dc|
  -- This is the standard triangle inequality for integers
  have h := Int.natAbs_add_le 
    ((depth S {S.primordial} a : ℤ) - (depth S {S.primordial} b : ℤ))
    ((depth S {S.primordial} b : ℤ) - (depth S {S.primordial} c : ℤ))
  simp only [sub_add_sub_cancel] at h
  simp only [Nat.cast_add]
  exact_mod_cast h

/-- Depth distance defines a pseudometric (metric up to identification) -/
noncomputable def depthPseudometric : PseudoMetricSpace S.Idea where
  dist := depthDistance
  dist_self a := by simp [depthDistance]
  dist_comm := depthDistance_symm
  dist_triangle := depthDistance_triangle
  edist a b := ENNReal.ofReal (depthDistance a b)
  edist_dist a b := by simp [depthDistance]

/-! ## Section 3: Continuity of Generation

Generation is continuous as a multi-valued function.
-/

/-- The preimage under generation is upward-closed when the target is upward-closed.
    This is a weaker but correct statement about generation continuity. -/
theorem generation_preimage_upward_closed (U : Set S.Idea) 
    (hU_open : @IsOpen S.Idea generationTopology U) :
    UpwardClosed {a | ∀ b ∈ S.generate a, b ∈ U} := by
  intro a ha c hc_gen
  -- a has property: all its generated ideas are in U
  -- c ∈ gen(a), need to show: all ideas generated from c are in U
  intro d hd_gen
  -- d ∈ gen(c) and c ∈ gen(a) and U is upward-closed
  -- Since c ∈ gen(a) and c ∈ {a | ∀ b ∈ gen(a), b ∈ U}, we have c ∈ U (from ha applied to c)
  have hc_U : c ∈ U := ha c hc_gen
  -- U is upward-closed, so d ∈ U
  exact hU_open c hc_U d hd_gen

/-! ## Section 4: Compactness Properties

The closure is generally not compact, but finite-depth subsets are.
-/

/-- Ideas up to depth n form a finite set (under finiteness assumptions) -/
theorem finite_depth_finite 
    (n : ℕ) 
    (h_finite_gen : ∀ a : S.Idea, (S.generate a).Finite) :
    (genCumulative S n {S.primordial}).Finite := by
  -- By induction on n
  induction n with
  | zero =>
    -- gen^0 = {primordial}
    unfold genCumulative
    exact Set.finite_singleton S.primordial
  | succ n ih =>
    -- gen^(n+1) = gen^n ∪ ⋃_{a ∈ gen^n} gen(a)
    unfold genCumulative
    apply Set.Finite.union ih
    -- ⋃_{a ∈ gen^n} gen(a) is finite as finite union of finite sets
    apply Set.Finite.biUnion ih
    exact fun a _ => h_finite_gen a

/-- Finite-depth sets are compact in the generation topology -/
theorem finite_depth_compact
    (n : ℕ)
    (h_finite_gen : ∀ a : S.Idea, (S.generate a).Finite) :
    @IsCompact S.Idea generationTopology (genCumulative S n {S.primordial}) := by
  -- Finite sets in any topology are compact
  have hfin : (genCumulative S n {S.primordial}).Finite := finite_depth_finite n h_finite_gen
  letI : TopologicalSpace S.Idea := generationTopology
  exact hfin.isCompact

/-! ## Section 5: Separability and Countability

Under countable generation, the space is separable.
-/

/-- If generation is countable, the closure is separable -/
theorem countable_generation_separable
    (h_countable : ∀ a : S.Idea, (S.generate a).Countable) :
    (SingleAgentIdeogenesis.closure S {S.primordial}).Countable := by
  -- The closure is the countable union of countable sets
  unfold SingleAgentIdeogenesis.closure
  apply Set.countable_iUnion
  intro n
  -- Show genCumulative S n {S.primordial} is countable by induction on n
  induction n with
  | zero =>
    -- gen^0 = {primordial}
    unfold genCumulative
    exact Set.countable_singleton S.primordial
  | succ n ih =>
    -- gen^(n+1) = gen^n ∪ ⋃_{a ∈ gen^n} gen(a)
    unfold genCumulative
    apply Set.Countable.union ih
    -- ⋃_{a ∈ gen^n} gen(a) is countable union of countable sets
    apply Set.Countable.biUnion ih
    exact fun a _ => h_countable a

/-! ## Section 6: Diameter and Boundedness

The diameter in depth metric grows with maximum depth.
-/

/-- The diameter of ideas up to depth n is at most n -/
theorem depth_diameter_bound (n : ℕ) :
    ∀ a b : S.Idea,
      a ∈ genCumulative S n {S.primordial} →
      b ∈ genCumulative S n {S.primordial} →
      depthDistance a b ≤ n := by
  intro a b ha hb
  have hda : depth S {S.primordial} a ≤ n := depth_le_of_mem S {S.primordial} a n ha
  have hdb : depth S {S.primordial} b ≤ n := depth_le_of_mem S {S.primordial} b n hb
  unfold depthDistance
  -- |da - db| ≤ max(da, db) ≤ n
  have : (Int.natAbs ((depth S {S.primordial} a : ℤ) - (depth S {S.primordial} b : ℤ)) : ℝ) ≤ n := by
    have h_bound : Int.natAbs ((depth S {S.primordial} a : ℤ) - (depth S {S.primordial} b : ℤ)) ≤ n := by
      by_cases h : depth S {S.primordial} a ≥ depth S {S.primordial} b
      · have : (depth S {S.primordial} a : ℤ) - (depth S {S.primordial} b : ℤ) = 
               ((depth S {S.primordial} a - depth S {S.primordial} b) : ℤ) := by
          simp [Int.ofNat_sub h]
        rw [this, Int.natAbs_ofNat]
        exact Nat.sub_le_of_le_add (by omega)
      · push_neg at h
        have h' : depth S {S.primordial} b > depth S {S.primordial} a := h
        have : (depth S {S.primordial} a : ℤ) - (depth S {S.primordial} b : ℤ) = 
               -((depth S {S.primordial} b - depth S {S.primordial} a) : ℤ) := by
          have : depth S {S.primordial} a ≤ depth S {S.primordial} b := Nat.le_of_lt h'
          simp [Int.ofNat_sub this]
          ring
        rw [this, Int.natAbs_neg, Int.natAbs_ofNat]
        exact Nat.sub_le_of_le_add (by omega)
    exact_mod_cast h_bound
  exact this

/-! ## Section 7: Completeness

The depth metric is complete in a sense - Cauchy sequences converge.
-/

/-- Cauchy sequences in depth metric converge (when they stabilize) -/
theorem depth_metric_complete 
    (seq : ℕ → S.Idea)
    (h_cauchy : ∀ ε > 0, ∃ N, ∀ m n, N ≤ m → N ≤ n → depthDistance (seq m) (seq n) < ε)
    (h_stabilize : ∃ N, ∀ n, N ≤ n → depth S {S.primordial} (seq n) = depth S {S.primordial} (seq N)) :
    ∃ limit : S.Idea, ∀ ε > 0, ∃ N, ∀ n, N ≤ n → depthDistance (seq n) limit < ε := by
  -- A Cauchy sequence that stabilizes in depth converges
  obtain ⟨N, hN⟩ := h_stabilize
  use seq N
  intro ε hε
  use N
  intro n hn
  -- seq n and seq N have the same depth by hN
  have heq : depth S {S.primordial} (seq n) = depth S {S.primordial} (seq N) := hN n hn
  have : depthDistance (seq n) (seq N) = 0 := by
    rw [depthDistance_zero_iff]
    exact heq
  rw [this]
  exact hε

/-! ## Section 8: Additional Theorems

Miscellaneous topological results.
-/

/-- Under grounded assumption, primordial ideogenetically generates everything -/
theorem primordial_generates_all_grounded 
    (h_grounded : ∀ a : S.Idea, a ∈ SingleAgentIdeogenesis.closure S {S.primordial}) :
    -- All ideas are in the ideogenetic closure
    ∀ a : S.Idea, ∃ n, a ∈ genCumulative S n {S.primordial} := by
  intro a
  have := h_grounded a
  unfold SingleAgentIdeogenesis.closure at this
  simp only [mem_iUnion] at this
  exact this

/-- Path-connected systems have all ideas reachable -/
theorem path_connected_grounded
    (h_paths : ∀ a b : S.Idea, 
      ∃ (path : List S.Idea), path.head? = some a ∧ path.getLast? = some b ∧
      ∀ i j : ℕ, i + 1 = j → j < path.length → 
        ∃ (pi : S.Idea) (pj : S.Idea), path[i]? = some pi ∧ path[j]? = some pj ∧ pj ∈ S.generate pi) :
    ∀ a : S.Idea, a ∈ SingleAgentIdeogenesis.closure S {S.primordial} := by
  intro a
  -- There's a generation path from primordial to a
  obtain ⟨path, h_start, h_end, h_edges⟩ := h_paths S.primordial a
  -- This path witnesses that a is in the closure
  -- The length of the path gives an upper bound on depth
  unfold SingleAgentIdeogenesis.closure
  simp only [mem_iUnion]
  -- We can show a appears at some stage ≤ path.length
  use path.length

/-- In locally compact generation topology, points have compact neighborhoods -/
theorem locally_compact_properties
    (h_lc : @LocallyCompactSpace S.Idea generationTopology) :
    ∀ a : S.Idea, ∃ (K : Set S.Idea), a ∈ K ∧ IsCompact K := by
  intro a
  -- Use local compactness to find compact neighborhood
  have := @LocallyCompactSpace.exists_compact_mem_nhds S.Idea generationTopology h_lc a
  obtain ⟨K, hK_compact, hK_nhd⟩ := this
  use K, hK_nhd, hK_compact

end IdeaTopology
